begin;
    
        
        
    

    

    merge into "AIRBYTE_DATABASE".TEST_NORMALIZATION."RENAMED_DEDUP_CDC_EXCLUDED" as DBT_INTERNAL_DEST
        using "AIRBYTE_DATABASE".TEST_NORMALIZATION."RENAMED_DEDUP_CDC_EXCLUDED__dbt_tmp" as DBT_INTERNAL_SOURCE
        on 
            DBT_INTERNAL_SOURCE._AIRBYTE_UNIQUE_KEY = DBT_INTERNAL_DEST._AIRBYTE_UNIQUE_KEY
        

    
    when matched then update set
        "_AIRBYTE_UNIQUE_KEY" = DBT_INTERNAL_SOURCE."_AIRBYTE_UNIQUE_KEY","ID" = DBT_INTERNAL_SOURCE."ID","_AIRBYTE_AB_ID" = DBT_INTERNAL_SOURCE."_AIRBYTE_AB_ID","_AIRBYTE_EMITTED_AT" = DBT_INTERNAL_SOURCE."_AIRBYTE_EMITTED_AT","_AIRBYTE_NORMALIZED_AT" = DBT_INTERNAL_SOURCE."_AIRBYTE_NORMALIZED_AT","_AIRBYTE_RENAMED_DEDUP_CDC_EXCLUDED_HASHID" = DBT_INTERNAL_SOURCE."_AIRBYTE_RENAMED_DEDUP_CDC_EXCLUDED_HASHID"
    

    when not matched then insert
        ("_AIRBYTE_UNIQUE_KEY", "ID", "_AIRBYTE_AB_ID", "_AIRBYTE_EMITTED_AT", "_AIRBYTE_NORMALIZED_AT", "_AIRBYTE_RENAMED_DEDUP_CDC_EXCLUDED_HASHID")
    values
        ("_AIRBYTE_UNIQUE_KEY", "ID", "_AIRBYTE_AB_ID", "_AIRBYTE_EMITTED_AT", "_AIRBYTE_NORMALIZED_AT", "_AIRBYTE_RENAMED_DEDUP_CDC_EXCLUDED_HASHID")

;
    commit;