/* tslint:disable */
/* eslint-disable */
/**
 * Airbyte Configuration API
 * Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Change Management: * The major version of the API endpoint can be determined / specified in the URL `localhost:8080/v1/connections/create` * Minor version bumps will be invisible to the end user. The user cannot specify minor versions in requests. * All backwards incompatible changes will happen in major version bumps. We will not make backwards incompatible changes in minor version bumps. Examples of non-breaking changes (includes but not limited to...):   * Adding fields to request or response bodies.   * Adding new HTTP endpoints. * All `web_backend` APIs are not considered public APIs and are not guaranteeing backwards compatibility. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@airbyte.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    DbMigrationExecutionRead,
    DbMigrationExecutionReadFromJSON,
    DbMigrationExecutionReadToJSON,
    DbMigrationReadList,
    DbMigrationReadListFromJSON,
    DbMigrationReadListToJSON,
    DbMigrationRequestBody,
    DbMigrationRequestBodyFromJSON,
    DbMigrationRequestBodyToJSON,
    InvalidInputExceptionInfo,
    InvalidInputExceptionInfoFromJSON,
    InvalidInputExceptionInfoToJSON,
    NotFoundKnownExceptionInfo,
    NotFoundKnownExceptionInfoFromJSON,
    NotFoundKnownExceptionInfoToJSON,
} from '../models';

export interface ExecuteMigrationsRequest {
    dbMigrationRequestBody: DbMigrationRequestBody;
}

export interface ListMigrationsRequest {
    dbMigrationRequestBody: DbMigrationRequestBody;
}

/**
 * 
 */
export class DbMigrationApi extends runtime.BaseAPI {

    /**
     * Migrate the database to the latest version
     */
    async executeMigrationsRaw(requestParameters: ExecuteMigrationsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<DbMigrationExecutionRead>> {
        if (requestParameters.dbMigrationRequestBody === null || requestParameters.dbMigrationRequestBody === undefined) {
            throw new runtime.RequiredError('dbMigrationRequestBody','Required parameter requestParameters.dbMigrationRequestBody was null or undefined when calling executeMigrations.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/db_migrations/migrate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DbMigrationRequestBodyToJSON(requestParameters.dbMigrationRequestBody),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DbMigrationExecutionReadFromJSON(jsonValue));
    }

    /**
     * Migrate the database to the latest version
     */
    async executeMigrations(requestParameters: ExecuteMigrationsRequest, initOverrides?: RequestInit): Promise<DbMigrationExecutionRead> {
        const response = await this.executeMigrationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all database migrations
     */
    async listMigrationsRaw(requestParameters: ListMigrationsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<DbMigrationReadList>> {
        if (requestParameters.dbMigrationRequestBody === null || requestParameters.dbMigrationRequestBody === undefined) {
            throw new runtime.RequiredError('dbMigrationRequestBody','Required parameter requestParameters.dbMigrationRequestBody was null or undefined when calling listMigrations.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/db_migrations/list`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DbMigrationRequestBodyToJSON(requestParameters.dbMigrationRequestBody),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DbMigrationReadListFromJSON(jsonValue));
    }

    /**
     * List all database migrations
     */
    async listMigrations(requestParameters: ListMigrationsRequest, initOverrides?: RequestInit): Promise<DbMigrationReadList> {
        const response = await this.listMigrationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
