package io.dataline.conduit.persistence;

public enum ConfigType {
  SOURCE_CONNECTION_CONFIGURATION,
  STANDARD_CONNECTION_STATUS,
  STANDARD_DISCOVERY_OUTPUT,
  DESTINATION_CONNECTION_CONFIGURATION,
  STANDARD_SYNC_CONFIGURATION,
  STANDARD_SYNC_SUMMARY,
  SYNC_STATE,
  SYNC_SCHEDULE
}
