package io.dataline.conduit.persistence;

public enum PersistenceConfigType {
  SOURCE_CONNECTION_CONFIGURATION,
  STANDARD_CONNECTION_STATUS,
  STANDARD_DISCOVERY_OUTPUT,
  DESTINATION_CONNECTION_CONFIGURATION,
  STANDARD_SYNC_CONFIGURATION,
  STANDARD_SYNC_SUMMARY,
  STANDARD_SYNC_STATE,
  STATE,
  STANDARD_SYNC_SCHEDULE
}
