

      create or replace transient table "AIRBYTE_DATABASE".TEST_NORMALIZATION."CONFLICT_STREAM_ARRAY"  as
      (
-- Final base SQL model
select
    ID,
    CONFLICT_STREAM_ARRAY,
    _airbyte_emitted_at,
    _AIRBYTE_CONFLICT_STREAM_ARRAY_HASHID
from "AIRBYTE_DATABASE"._AIRBYTE_TEST_NORMALIZATION."CONFLICT_STREAM_ARRAY_AB3"
-- CONFLICT_STREAM_ARRAY from "AIRBYTE_DATABASE".TEST_NORMALIZATION._AIRBYTE_RAW_CONFLICT_STREAM_ARRAY
      );
    