

      create or replace transient table "AIRBYTE_DATABASE".TEST_NORMALIZATION."UNNEST_ALIAS"  as
      (
-- Final base SQL model
select
    ID,
    CHILDREN,
    _airbyte_emitted_at,
    _AIRBYTE_UNNEST_ALIAS_HASHID
from "AIRBYTE_DATABASE"._AIRBYTE_TEST_NORMALIZATION."UNNEST_ALIAS_AB3"
-- UNNEST_ALIAS from "AIRBYTE_DATABASE".TEST_NORMALIZATION._AIRBYTE_RAW_UNNEST_ALIAS
      );
    