connector_image: airbyte/destination-altertable:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: destination_altertable/spec.json
        config_path: "integration_tests/config.json"
  connection:
    tests:
      - config_path: "integration_tests/config.json"
        status: "succeed"
