# See [Connector Acceptance Tests](https://docs.airbyte.com/connector-development/testing-connectors/connector-acceptance-tests-reference)
# for more information about how to configure these tests
connector_image: airbyte/source-kapa:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: "manifest.yaml"
  connection:
    bypass_reason: "No Kapa test credentials are available"
  discovery:
    bypass_reason: "No Kapa test credentials are available"
  basic_read:
    bypass_reason: "No Kapa test credentials are available"
  incremental:
    bypass_reason: "No Kapa test credentials are available"
  full_refresh:
    bypass_reason: "No Kapa test credentials are available"
