/**
 * This script cleans up the temporary registry cache file after the build is complete.
 * The cache file is generated during the prebuild phase and should not be
 * committed to git since it's regenerated on each build.
 *
 * Note: the agent connector manifest (src/data/agent_connectors.json) is
 * intentionally NOT cleaned up here. It's imported directly by
 * AgentConnectorRegistry.jsx, so the file must exist on disk for any
 * build/start invocation — including ones that bypass the prebuild/prestart
 * hooks (e.g. calling `docusaurus build` directly). It's committed to git and
 * regenerated by prepare-agent-connector-manifest.js on each prebuild.
 */
const fs = require("fs");
const { REGISTRY_CACHE_PATH } = require("./constants");

function cleanupFile(filePath) {
  if (fs.existsSync(filePath)) {
    try {
      fs.unlinkSync(filePath);
      console.log(`Cleaned up cache file: ${filePath}`);
    } catch (error) {
      console.warn(`Failed to clean up ${filePath}:`, error.message);
    }
  }
}

function cleanupCache() {
  cleanupFile(REGISTRY_CACHE_PATH);
}

cleanupCache();
