# Use the official Python 3.10 image as the base image
FROM python:3.10

# Set the working directory inside the container
WORKDIR /app

# Clone the specified branch from the GitHub repository
RUN git clone --single-branch --branch master https://github.com/airbytehq/airbyte.git

# Copy the binary file from the host machine to the container's working directory
COPY ./airbyte-ci/connectors/pipelines/dist/airbyte_ci /app/airbyte_ci

# Run the binary file with the specified command
CMD ["./airbyte_ci", "--version"]

