FROM airbyte/base-python-test:dev

# Bash is installed for convenient debugging.
RUN apt-get update && apt-get install -y gcc bash && rm -rf /var/lib/apt/lists/*

ENV MODULE_NAME="source_shopify_singer"
ENV CODE_PATH="integration_tests"
ENV AIRBYTE_TEST_MODULE="integration_tests"
ENV AIRBYTE_TEST_PATH="SourceShopifySingerStandardTest"

LABEL io.airbyte.version=0.1.0
LABEL io.airbyte.name=airbyte/source-shopify-singer-standard-test

WORKDIR /airbyte/integration_code
COPY $MODULE_NAME $MODULE_NAME
COPY $CODE_PATH $CODE_PATH
COPY secrets/config.json $CODE_PATH/config.json
COPY $MODULE_NAME/*.json $CODE_PATH/
COPY setup.py ./

RUN pip install https://github.com/airbytehq/tap-shopify/tarball/master
RUN pip install ".[tests]"

WORKDIR /airbyte
