#
# Copyright (c) 2023 Airbyte, Inc., all rights reserved.
#


import json

from typing import Dict, Generator


from airbyte_cdk.logger import AirbyteLogger
from airbyte_cdk.models import (
    AirbyteCatalog,
    AirbyteConnectionStatus,
    AirbyteMessage,
    AirbyteStream,
    ConfiguredAirbyteCatalog,
    Status,
)
from airbyte_cdk.sources import Source

from source_adaptive.adaptive.base import get_config_as_dict
from source_adaptive.adaptive.factory_adaptive import generate_adaptive_method

class SourceAdaptive(Source):
    """
    The way the custom source adaptive is designed, simply uses the factory method
    'generate_adaptive_method' to create the respective method actually wanted.
    Should the custom airbyte implementation changes, no to little changes
    will be needed to upgrade this custom source.
    """
    def check(self, logger: AirbyteLogger, config: json) -> AirbyteConnectionStatus:
        """
        Tests if the input configuration can be used to successfully connect to the integration
            e.g: if a provided Stripe API token can be used to connect to the Stripe API.

        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json is as specified in
        the properties of the spec.yaml file

        :return: AirbyteConnectionStatus indicating a Success or Failure
        """
        try:
            adaptive_method = generate_adaptive_method(logger = logger,config = config)

            method = get_config_as_dict(config)["method_obj"]["method"]
            if adaptive_method is None:
                return AirbyteConnectionStatus(status=Status.FAILED, message=f"method: {method} has not been implemented yet")

            # make the request and keep the response
            response = adaptive_method.perform_request_fast()

            if not (adaptive_method.is_request_successful(response=response)):
                error_message = adaptive_method.get_request_error_messages(response=response)
                return AirbyteConnectionStatus(status=Status.FAILED, message=f"An exception occurred: reason(s)={error_message}")

            return AirbyteConnectionStatus(status=Status.SUCCEEDED)
        except Exception as e:
            return AirbyteConnectionStatus(status=Status.FAILED, message=f"An exception occurred: {str(e)}")

    def discover(self, logger: AirbyteLogger, config: json) -> AirbyteCatalog:
        """
        Returns an AirbyteCatalog representing the available streams and fields in this integration.
        For example, given valid credentials to a Postgres database,
        returns an Airbyte catalog where each postgres table is a stream, and each table column is a field.

        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json is as specified in
        the properties of the spec.yaml file

        :return: AirbyteCatalog is an object describing a list of all available streams in this source.
            A stream is an AirbyteStream object that includes:
            - its stream name (or table name in the case of Postgres)
            - json_schema providing the specifications of expected schema for this stream (a list of columns described
            by their names and types)
        """

        streams = []

        supported_sync_modes = ["full_refresh"]
        source_defined_cursor = False
        adaptive_method = generate_adaptive_method(logger = logger,config = config)
        streams.append(
            AirbyteStream(
                name=adaptive_method.generate_table_name(),
                json_schema=adaptive_method.generate_table_schema(),
                supported_sync_modes=supported_sync_modes,
                source_defined_cursor=source_defined_cursor,
            )
        )

        return AirbyteCatalog(streams=streams)

    def read(
        self, logger: AirbyteLogger, config: json, catalog: ConfiguredAirbyteCatalog, state: Dict[str, any]
    ) -> Generator[AirbyteMessage, None, None]:
        """
        Returns a generator of the AirbyteMessages generated by reading the source with the given configuration,
        catalog, and state.

        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json is as specified in
            the properties of the spec.yaml file
        :param catalog: The input catalog is a ConfiguredAirbyteCatalog which is almost the same as AirbyteCatalog
            returned by discover(), but
        in addition, it's been configured in the UI! For each particular stream and field, there may have been provided
        with extra modifications such as: filtering streams and/or columns out, renaming some entities, etc
        :param state: When a Airbyte reads data from a source, it might need to keep a checkpoint cursor to resume
            replication in the future from that saved checkpoint.
            This is the object that is provided with state from previous runs and avoid replicating the entire set of
            data everytime.

        :return: A generator that produces a stream of AirbyteRecordMessage contained in AirbyteMessage object.
        """

        adaptive_method = generate_adaptive_method(logger = logger,config = config)
        return adaptive_method.generate_table_row()

