#
# Copyright (c) 2023 Airbyte, Inc., all rights reserved.
#

import base64
import json
import logging
import re
import time
from dataclasses import InitVar, dataclass
from http import HTTPStatus
from typing import Any, Iterable, List, Mapping, MutableMapping, Optional, Union

import requests
from requests import HTTPError

from airbyte_cdk.sources.declarative.auth.declarative_authenticator import NoAuth
from airbyte_cdk.sources.declarative.extractors.record_extractor import RecordExtractor
from airbyte_cdk.sources.declarative.interpolation import InterpolatedString
from airbyte_cdk.sources.declarative.types import Config
from airbyte_cdk.sources.types import StreamSlice


# https://developers.zoom.us/docs/internal-apps/s2s-oauth/#successful-response
# The Bearer token generated by server-to-server token will expire in one hour
BEARER_TOKEN_EXPIRES_IN = 3590
ZOOM_API_BASE = "https://api.zoom.us/v2"

# Shared access-token cache so the manifest authenticator and the custom
# extractors do not each mint a separate token. Keyed by (client_id, account_id).
# value = {"access_token": str, "generated_at": float}
_TOKEN_CACHE: MutableMapping[tuple, MutableMapping[str, Any]] = {}


@dataclass
class ServerToServerOauthAuthenticator(NoAuth):
    config: Config
    account_id: Union[InterpolatedString, str]
    client_id: Union[InterpolatedString, str]
    client_secret: Union[InterpolatedString, str]
    authorization_endpoint: Union[InterpolatedString, str]

    _grant_type = "account_credentials"

    def __post_init__(self, parameters: Mapping[str, Any]):
        self._account_id = InterpolatedString.create(self.account_id, parameters=parameters).eval(self.config)
        self._client_id = InterpolatedString.create(self.client_id, parameters=parameters).eval(self.config)
        self._client_secret = InterpolatedString.create(self.client_secret, parameters=parameters).eval(self.config)
        self._authorization_endpoint = InterpolatedString.create(self.authorization_endpoint, parameters=parameters).eval(self.config)

    def __call__(self, request: requests.PreparedRequest) -> requests.PreparedRequest:
        """Attach a (cached, auto-refreshing) bearer token to the request."""
        request.headers.update(
            {
                "Authorization": f"Bearer {self._get_valid_token()}",
                "Content-type": "application/json",
            }
        )
        return request

    @property
    def auth_header(self) -> str:
        return "Authorization"

    @property
    def token(self) -> Optional[str]:
        entry = _TOKEN_CACHE.get(self._cache_key())
        return entry["access_token"] if entry else None

    def _cache_key(self) -> tuple:
        return (self._client_id, self._account_id)

    def _get_valid_token(self) -> str:
        key = self._cache_key()
        entry = _TOKEN_CACHE.get(key)
        if entry is None or (time.time() - entry["generated_at"]) > BEARER_TOKEN_EXPIRES_IN:
            entry = {"access_token": self.generate_access_token(), "generated_at": time.time()}
            _TOKEN_CACHE[key] = entry
        return entry["access_token"]

    def generate_access_token(self) -> str:
        try:
            token = base64.b64encode(f"{self._client_id}:{self._client_secret}".encode("ascii")).decode("utf-8")
            headers = {"Authorization": f"Basic {token}", "Content-type": "application/json"}
            rest = requests.post(
                url=f"{self._authorization_endpoint}?grant_type={self._grant_type}&account_id={self._account_id}", headers=headers
            )
            if rest.status_code != HTTPStatus.OK:
                raise HTTPError(rest.text)
            return rest.json().get("access_token")
        except Exception as e:
            raise Exception(f"Error while generating access token: {e}") from e


def parse_vtt_content(vtt_content: str) -> List[MutableMapping[str, Any]]:
    """
    Parse WebVTT content into structured records.

    VTT Format Example:
        WEBVTT

        1
        00:00:05.000 --> 00:00:08.500
        Ryan Waskewich: Hello, this is a test recording.

        2
        00:00:09.000 --> 00:00:12.000
        For the Airbyte connector transcript feature.

    Returns a list of records with sequence, start, end, speaker, and text fields.
    """
    records = []

    # Split by double newlines to get cue blocks
    # Handle both \r\n and \n line endings
    vtt_content = vtt_content.replace("\r\n", "\n")

    # Remove WEBVTT header and any metadata
    lines = vtt_content.strip().split("\n")
    if lines and lines[0].startswith("WEBVTT"):
        lines = lines[1:]

    # Join back and split by empty lines to get cue blocks
    content = "\n".join(lines)
    cue_blocks = re.split(r"\n\n+", content.strip())

    sequence = 0
    for block in cue_blocks:
        block = block.strip()
        if not block:
            continue

        block_lines = block.split("\n")

        # Find the timestamp line (contains "-->")
        timestamp_line_idx = None
        for i, line in enumerate(block_lines):
            if "-->" in line:
                timestamp_line_idx = i
                break

        if timestamp_line_idx is None:
            continue

        # Parse timestamp line
        timestamp_line = block_lines[timestamp_line_idx]
        timestamp_match = re.match(
            r"(\d{2}:\d{2}:\d{2}[.,]\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2}[.,]\d{3})",
            timestamp_line,
        )

        if not timestamp_match:
            continue

        sequence += 1
        start_time = timestamp_match.group(1).replace(",", ".")
        end_time = timestamp_match.group(2).replace(",", ".")

        # Get text lines (everything after timestamp)
        text_lines = block_lines[timestamp_line_idx + 1 :]
        text = " ".join(line.strip() for line in text_lines if line.strip())

        # Try to extract speaker from text (format: "Speaker Name: text")
        speaker = None
        speaker_match = re.match(r"^([^:]+):\s*(.+)$", text)
        if speaker_match:
            potential_speaker = speaker_match.group(1).strip()
            # Only treat as speaker if it looks like a name (not too long, no special chars)
            if len(potential_speaker) < 50 and not re.search(r"[<>\[\]]", potential_speaker):
                speaker = potential_speaker
                text = speaker_match.group(2).strip()

        records.append(
            {
                "sequence_number": sequence,
                "timestamp_start": start_time,
                "timestamp_end": end_time,
                "speaker": speaker,
                "text": text,
            }
        )

    return records


@dataclass
class TranscriptContentExtractor(RecordExtractor):
    """
    Custom record extractor that fetches and parses VTT transcript content.

    This extractor:
    1. Gets the recording data from the API response
    2. Filters for recording_files with file_type == "TRANSCRIPT"
    3. Fetches the VTT content from the download_url
    4. Parses the VTT into structured transcript records
    5. Yields enriched records with meeting metadata
    """

    config: Config
    parameters: InitVar[Mapping[str, Any]]

    def __post_init__(self, parameters: Mapping[str, Any]) -> None:
        self._parameters = parameters
        self._logger = logging.getLogger("airbyte.TranscriptContentExtractor")
        self._authenticator: Optional[ServerToServerOauthAuthenticator] = None

    def _get_authenticator(self) -> ServerToServerOauthAuthenticator:
        """Get or create the authenticator instance."""
        if self._authenticator is None:
            self._authenticator = ServerToServerOauthAuthenticator(
                config=self.config,
                account_id=self.config.get("account_id", ""),
                client_id=self.config.get("client_id", ""),
                client_secret=self.config.get("client_secret", ""),
                authorization_endpoint=self.config.get("authorization_endpoint", "https://zoom.us/oauth/token"),
                parameters={},
            )
        return self._authenticator

    def _fetch_transcript_content(self, download_url: str) -> Optional[str]:
        """Fetch VTT content from the download URL with authentication."""
        try:
            response = requests.get(download_url, auth=self._get_authenticator(), timeout=60)
            response.raise_for_status()
            return response.text
        except Exception as e:
            self._logger.warning(f"Failed to fetch transcript from {download_url}: {e}")
            return None

    def extract_records(
        self,
        response: requests.Response,
        stream_slice: Optional[StreamSlice] = None,
        **kwargs: Any,
    ) -> Iterable[MutableMapping[str, Any]]:
        """
        Extract transcript records from the recordings API response.

        For each recording in the response, this method:
        1. Filters for transcript files in recording_files
        2. Fetches and parses the VTT content
        3. Yields structured transcript records
        """
        try:
            response_json = response.json()
        except (ValueError, json.JSONDecodeError) as e:
            self._logger.warning(f"Failed to parse response JSON: {e}")
            return

        # Get recordings from the response (they're in the "meetings" array)
        recordings = response_json.get("meetings", [])

        for recording in recordings:
            # Get recording metadata
            meeting_id = recording.get("id") or recording.get("uuid", "")
            meeting_topic = recording.get("topic", "")
            meeting_uuid = recording.get("uuid", "")
            host_id = recording.get("host_id", "")
            start_time = recording.get("start_time", "")

            # Get recording files
            recording_files = recording.get("recording_files", [])

            for recording_file in recording_files:
                file_type = recording_file.get("file_type", "")
                recording_type = recording_file.get("recording_type", "")

                # Filter for transcript files only
                if file_type != "TRANSCRIPT" and recording_type != "audio_transcript":
                    continue

                download_url = recording_file.get("download_url")
                if not download_url:
                    continue

                recording_id = recording_file.get("id", "")

                # Fetch and parse the VTT content
                vtt_content = self._fetch_transcript_content(download_url)
                if not vtt_content:
                    continue

                transcript_records = parse_vtt_content(vtt_content)

                # Yield enriched records
                for record in transcript_records:
                    enriched_record = {
                        "meeting_id": str(meeting_id),
                        "meeting_uuid": meeting_uuid,
                        "meeting_topic": meeting_topic,
                        "host_id": host_id,
                        "meeting_start_time": start_time,
                        "recording_id": recording_id,
                        **record,
                    }
                    yield enriched_record


@dataclass
class PhoneTranscriptContentExtractor(RecordExtractor):
    """
    Custom record extractor that fetches and parses Zoom Phone recording transcripts.

    This extractor:
    1. Gets the phone recordings from the /phone/recordings API response
    2. For each recording, fetches the transcript from /phone/recording_transcript/download/{recordingId}
    3. Parses the transcript content (VTT or plain text)
    4. Yields enriched records with call metadata
    """

    config: Config
    parameters: InitVar[Mapping[str, Any]]

    def __post_init__(self, parameters: Mapping[str, Any]) -> None:
        self._parameters = parameters
        self._logger = logging.getLogger("airbyte.PhoneTranscriptContentExtractor")
        self._authenticator: Optional[ServerToServerOauthAuthenticator] = None

    def _get_authenticator(self) -> ServerToServerOauthAuthenticator:
        """Get or create the authenticator instance."""
        if self._authenticator is None:
            self._authenticator = ServerToServerOauthAuthenticator(
                config=self.config,
                account_id=self.config.get("account_id", ""),
                client_id=self.config.get("client_id", ""),
                client_secret=self.config.get("client_secret", ""),
                authorization_endpoint=self.config.get("authorization_endpoint", "https://zoom.us/oauth/token"),
                parameters={},
            )
        return self._authenticator

    def _fetch_transcript(self, recording_id: str) -> Optional[str]:
        """Fetch transcript content from the phone recording transcript download endpoint."""
        try:
            url = f"{ZOOM_API_BASE}/phone/recording_transcript/download/{recording_id}"
            response = requests.get(url, auth=self._get_authenticator(), timeout=60)

            if response.status_code == 404:
                return None

            response.raise_for_status()

            # Check if the response is a JSON error
            try:
                json_response = response.json()
                if "code" in json_response:
                    self._logger.debug(
                        f"Transcript not available for recording {recording_id}: {json_response.get('message', 'Unknown error')}"
                    )
                    return None
            except (ValueError, json.JSONDecodeError):
                pass  # Not JSON, which is expected for transcript content

            return response.text
        except Exception as e:
            self._logger.warning(f"Failed to fetch transcript for recording {recording_id}: {e}")
            return None

    def extract_records(
        self,
        response: requests.Response,
        stream_slice: Optional[StreamSlice] = None,
        **kwargs: Any,
    ) -> Iterable[MutableMapping[str, Any]]:
        """
        Extract transcript records from the phone recordings API response.

        For each recording, this method fetches the transcript and yields structured records.
        """
        try:
            response_json = response.json()
        except (ValueError, json.JSONDecodeError) as e:
            self._logger.warning(f"Failed to parse response JSON: {e}")
            return

        recordings = response_json.get("recordings", [])

        for recording in recordings:
            recording_id = recording.get("id", "")
            if not recording_id:
                continue

            call_id = recording.get("call_id", "")
            call_log_id = recording.get("call_log_id", "")
            caller_name = recording.get("caller_name", "")
            caller_number = recording.get("caller_number", "")
            callee_name = recording.get("callee_name", "")
            callee_number = recording.get("callee_number", "")
            direction = recording.get("direction", "")
            date_time = recording.get("date_time", "")
            duration = recording.get("duration", 0)
            owner = recording.get("owner", {})

            transcript_content = self._fetch_transcript(recording_id)
            if not transcript_content:
                continue

            # Check if VTT format and parse accordingly
            if transcript_content.strip().startswith("WEBVTT"):
                transcript_records = parse_vtt_content(transcript_content)
                for record in transcript_records:
                    yield {
                        "recording_id": recording_id,
                        "call_id": call_id,
                        "call_log_id": call_log_id,
                        "caller_name": caller_name,
                        "caller_number": caller_number,
                        "callee_name": callee_name,
                        "callee_number": callee_number,
                        "direction": direction,
                        "call_date_time": date_time,
                        "call_duration": duration,
                        "owner_id": owner.get("id", "") if isinstance(owner, dict) else "",
                        "owner_name": owner.get("name", "") if isinstance(owner, dict) else "",
                        **record,
                    }
            else:
                # Return as a single text record for non-VTT transcripts
                yield {
                    "recording_id": recording_id,
                    "call_id": call_id,
                    "call_log_id": call_log_id,
                    "caller_name": caller_name,
                    "caller_number": caller_number,
                    "callee_name": callee_name,
                    "callee_number": callee_number,
                    "direction": direction,
                    "call_date_time": date_time,
                    "call_duration": duration,
                    "owner_id": owner.get("id", "") if isinstance(owner, dict) else "",
                    "owner_name": owner.get("name", "") if isinstance(owner, dict) else "",
                    "sequence_number": 1,
                    "timestamp_start": None,
                    "timestamp_end": None,
                    "speaker": None,
                    "text": transcript_content.strip(),
                }
