FROM airbyte/base-python-test:dev

RUN apt-get update && rm -rf /var/lib/apt/lists/*

ENV CODE_PATH="integration_tests"
ENV AIRBYTE_TEST_MODULE="integration_tests"
ENV AIRBYTE_TEST_PATH="Source{{properCase name}}StandardTest"
ENV AIRBYTE_TEST_CASE=true

LABEL io.airbyte.version=0.1.0
LABEL io.airbyte.name=airbyte/source-{{dashCase name}}-standard-test

WORKDIR /airbyte/integration_code
COPY source_{{snakeCase name}} source_{{snakeCase name}}
COPY $CODE_PATH $CODE_PATH
COPY secrets/* $CODE_PATH
COPY source_{{snakeCase name}}/*.json $CODE_PATH
COPY setup.py ./

RUN pip install ".[tests]"

WORKDIR /airbyte
