FROM airbyte/base-python-test:dev

RUN apt-get update && rm -rf /var/lib/apt/lists/*

ENV CODE_PATH="integration_tests"
ENV AIRBYTE_TEST_MODULE="integration_tests"
ENV AIRBYTE_TEST_PATH="{{properCase name}}SourceStandardTest"
ENV AIRBYTE_TEST_CASE=true

LABEL io.airbyte.version=0.1.0
LABEL io.airbyte.name=airbyte/source-{{dashCase name}}-standard-test

WORKDIR /airbyte/integration_code
COPY {{snakeCase name}}_source {{snakeCase name}}_source
COPY $CODE_PATH $CODE_PATH
COPY secrets/* $CODE_PATH
COPY {{snakeCase name}}_source/*.json $CODE_PATH
COPY setup.py ./

RUN pip install ".[integration_tests]"

WORKDIR /airbyte
