#!/bin/bash

airbyte-ci connectors --name source-activecampaign migrate_to_base_image
airbyte-ci connectors --name source-aha migrate_to_base_image
airbyte-ci connectors --name source-aircall migrate_to_base_image
airbyte-ci connectors --name source-alpha-vantage migrate_to_base_image
airbyte-ci connectors --name source-apify-dataset migrate_to_base_image
airbyte-ci connectors --name source-appfollow migrate_to_base_image
airbyte-ci connectors --name source-apple-search-ads migrate_to_base_image
airbyte-ci connectors --name source-appsflyer migrate_to_base_image
airbyte-ci connectors --name source-asana migrate_to_base_image
airbyte-ci connectors --name source-ashby migrate_to_base_image
airbyte-ci connectors --name source-aws-cloudtrail migrate_to_base_image
airbyte-ci connectors --name source-babelforce migrate_to_base_image
airbyte-ci connectors --name source-bamboo-hr migrate_to_base_image
airbyte-ci connectors --name source-bigcommerce migrate_to_base_image
airbyte-ci connectors --name source-braintree migrate_to_base_image
airbyte-ci connectors --name source-braze migrate_to_base_image
airbyte-ci connectors --name source-breezometer migrate_to_base_image
airbyte-ci connectors --name source-callrail migrate_to_base_image
airbyte-ci connectors --name source-captain-data migrate_to_base_image
airbyte-ci connectors --name source-cart migrate_to_base_image
airbyte-ci connectors --name source-chargify migrate_to_base_image
airbyte-ci connectors --name source-chartmogul migrate_to_base_image
airbyte-ci connectors --name source-clickup-api migrate_to_base_image
airbyte-ci connectors --name source-clockify migrate_to_base_image
airbyte-ci connectors --name source-close-com migrate_to_base_image
airbyte-ci connectors --name source-coda migrate_to_base_image
airbyte-ci connectors --name source-coin-api migrate_to_base_image
airbyte-ci connectors --name source-coingecko-coins migrate_to_base_image
airbyte-ci connectors --name source-coinmarketcap migrate_to_base_image
airbyte-ci connectors --name source-commercetools migrate_to_base_image
airbyte-ci connectors --name source-configcat migrate_to_base_image
airbyte-ci connectors --name source-confluence migrate_to_base_image
airbyte-ci connectors --name source-convertkit migrate_to_base_image
airbyte-ci connectors --name source-copper migrate_to_base_image
airbyte-ci connectors --name source-customer-io migrate_to_base_image
airbyte-ci connectors --name source-datadog migrate_to_base_image
airbyte-ci connectors --name source-datascope migrate_to_base_image
airbyte-ci connectors --name source-delighted migrate_to_base_image
airbyte-ci connectors --name source-dixa migrate_to_base_image
airbyte-ci connectors --name source-dockerhub migrate_to_base_image
airbyte-ci connectors --name source-dremio migrate_to_base_image
airbyte-ci connectors --name source-drift migrate_to_base_image
airbyte-ci connectors --name source-emailoctopus migrate_to_base_image
airbyte-ci connectors --name source-everhour migrate_to_base_image
airbyte-ci connectors --name source-exchange-rates migrate_to_base_image
airbyte-ci connectors --name source-fastbill migrate_to_base_image
airbyte-ci connectors --name source-freshcaller migrate_to_base_image
airbyte-ci connectors --name source-freshsales migrate_to_base_image
airbyte-ci connectors --name source-freshservice migrate_to_base_image
airbyte-ci connectors --name source-fullstory migrate_to_base_image
airbyte-ci connectors --name source-gainsight-px migrate_to_base_image
airbyte-ci connectors --name source-genesys migrate_to_base_image
airbyte-ci connectors --name source-getlago migrate_to_base_image
airbyte-ci connectors --name source-glassfrog migrate_to_base_image
airbyte-ci connectors --name source-gocardless migrate_to_base_image
airbyte-ci connectors --name source-gong migrate_to_base_image
airbyte-ci connectors --name source-google-directory migrate_to_base_image
airbyte-ci connectors --name source-google-pagespeed-insights migrate_to_base_image
airbyte-ci connectors --name source-google-webfonts migrate_to_base_image
airbyte-ci connectors --name source-gutendex migrate_to_base_image
airbyte-ci connectors --name source-harness migrate_to_base_image
airbyte-ci connectors --name source-hellobaton migrate_to_base_image
airbyte-ci connectors --name source-hubplanner migrate_to_base_image
airbyte-ci connectors --name source-insightly migrate_to_base_image
airbyte-ci connectors --name source-instatus migrate_to_base_image
airbyte-ci connectors --name source-intruder migrate_to_base_image
airbyte-ci connectors --name source-ip2whois migrate_to_base_image
airbyte-ci connectors --name source-k6-cloud migrate_to_base_image
airbyte-ci connectors --name source-klarna migrate_to_base_image
airbyte-ci connectors --name source-klaus-api migrate_to_base_image
airbyte-ci connectors --name source-launchdarkly migrate_to_base_image
airbyte-ci connectors --name source-lemlist migrate_to_base_image
airbyte-ci connectors --name source-linkedin-pages migrate_to_base_image
airbyte-ci connectors --name source-lokalise migrate_to_base_image
airbyte-ci connectors --name source-looker migrate_to_base_image
airbyte-ci connectors --name source-mailerlite migrate_to_base_image
airbyte-ci connectors --name source-mailersend migrate_to_base_image
airbyte-ci connectors --name source-mailgun migrate_to_base_image
airbyte-ci connectors --name source-mailjet-mail migrate_to_base_image
airbyte-ci connectors --name source-mailjet-sms migrate_to_base_image
airbyte-ci connectors --name source-merge migrate_to_base_image
airbyte-ci connectors --name source-microsoft-teams migrate_to_base_image
airbyte-ci connectors --name source-my-hours migrate_to_base_image
airbyte-ci connectors --name source-n8n migrate_to_base_image
airbyte-ci connectors --name source-nasa migrate_to_base_image
airbyte-ci connectors --name source-news-api migrate_to_base_image
airbyte-ci connectors --name source-newsdata migrate_to_base_image
airbyte-ci connectors --name source-nytimes migrate_to_base_image
airbyte-ci connectors --name source-okta migrate_to_base_image
airbyte-ci connectors --name source-omnisend migrate_to_base_image
airbyte-ci connectors --name source-onesignal migrate_to_base_image
airbyte-ci connectors --name source-open-exchange-rates migrate_to_base_image
airbyte-ci connectors --name source-openweather migrate_to_base_image
airbyte-ci connectors --name source-opsgenie migrate_to_base_image
airbyte-ci connectors --name source-orbit migrate_to_base_image
airbyte-ci connectors --name source-oura migrate_to_base_image
airbyte-ci connectors --name source-outbrain-amplify migrate_to_base_image
airbyte-ci connectors --name source-outreach migrate_to_base_image
airbyte-ci connectors --name source-pagerduty migrate_to_base_image
airbyte-ci connectors --name source-pardot migrate_to_base_image
airbyte-ci connectors --name source-partnerstack migrate_to_base_image
airbyte-ci connectors --name source-paystack migrate_to_base_image
airbyte-ci connectors --name source-pendo migrate_to_base_image
airbyte-ci connectors --name source-persistiq migrate_to_base_image
airbyte-ci connectors --name source-pexels-api migrate_to_base_image
airbyte-ci connectors --name source-pipedrive migrate_to_base_image
airbyte-ci connectors --name source-pivotal-tracker migrate_to_base_image
airbyte-ci connectors --name source-plaid migrate_to_base_image
airbyte-ci connectors --name source-plausible migrate_to_base_image
airbyte-ci connectors --name source-pocket migrate_to_base_image
airbyte-ci connectors --name source-pokeapi migrate_to_base_image
airbyte-ci connectors --name source-polygon-stock-api migrate_to_base_image
airbyte-ci connectors --name source-posthog migrate_to_base_image
airbyte-ci connectors --name source-postmarkapp migrate_to_base_image
airbyte-ci connectors --name source-prestashop migrate_to_base_image
airbyte-ci connectors --name source-primetric migrate_to_base_image
airbyte-ci connectors --name source-public-apis migrate_to_base_image
airbyte-ci connectors --name source-punk-api migrate_to_base_image
airbyte-ci connectors --name source-pypi migrate_to_base_image
airbyte-ci connectors --name source-python-http-tutorial migrate_to_base_image
airbyte-ci connectors --name source-qonto migrate_to_base_image
airbyte-ci connectors --name source-qualaroo migrate_to_base_image
airbyte-ci connectors --name source-railz migrate_to_base_image
airbyte-ci connectors --name source-rd-station-marketing migrate_to_base_image
airbyte-ci connectors --name source-recreation migrate_to_base_image
airbyte-ci connectors --name source-recruitee migrate_to_base_image
airbyte-ci connectors --name source-reply-io migrate_to_base_image
airbyte-ci connectors --name source-retently migrate_to_base_image
airbyte-ci connectors --name source-ringcentral migrate_to_base_image
airbyte-ci connectors --name source-rki-covid migrate_to_base_image
airbyte-ci connectors --name source-rocket-chat migrate_to_base_image
airbyte-ci connectors --name source-rss migrate_to_base_image
airbyte-ci connectors --name source-salesloft migrate_to_base_image
airbyte-ci connectors --name source-sap-fieldglass migrate_to_base_image
airbyte-ci connectors --name source-secoda migrate_to_base_image
airbyte-ci connectors --name source-sendinblue migrate_to_base_image
airbyte-ci connectors --name source-senseforce migrate_to_base_image
airbyte-ci connectors --name source-serpstat migrate_to_base_image
airbyte-ci connectors --name source-shortio migrate_to_base_image
airbyte-ci connectors --name source-smaily migrate_to_base_image
airbyte-ci connectors --name source-smartengage migrate_to_base_image
airbyte-ci connectors --name source-sonar-cloud migrate_to_base_image
airbyte-ci connectors --name source-spacex-api migrate_to_base_image
airbyte-ci connectors --name source-square migrate_to_base_image
airbyte-ci connectors --name source-statuspage migrate_to_base_image
airbyte-ci connectors --name source-strava migrate_to_base_image
airbyte-ci connectors --name source-survey-sparrow migrate_to_base_image
airbyte-ci connectors --name source-tempo migrate_to_base_image
airbyte-ci connectors --name source-the-guardian-api migrate_to_base_image
airbyte-ci connectors --name source-timely migrate_to_base_image
airbyte-ci connectors --name source-tmdb migrate_to_base_image
airbyte-ci connectors --name source-toggl migrate_to_base_image
airbyte-ci connectors --name source-tplcentral migrate_to_base_image
airbyte-ci connectors --name source-trello migrate_to_base_image
airbyte-ci connectors --name source-trustpilot migrate_to_base_image
airbyte-ci connectors --name source-tvmaze-schedule migrate_to_base_image
airbyte-ci connectors --name source-twilio-taskrouter migrate_to_base_image
airbyte-ci connectors --name source-twitter migrate_to_base_image
airbyte-ci connectors --name source-tyntec-sms migrate_to_base_image
airbyte-ci connectors --name source-unleash migrate_to_base_image
airbyte-ci connectors --name source-vantage migrate_to_base_image
airbyte-ci connectors --name source-visma-economic migrate_to_base_image
airbyte-ci connectors --name source-vitally migrate_to_base_image
airbyte-ci connectors --name source-waiteraid migrate_to_base_image
airbyte-ci connectors --name source-weatherstack migrate_to_base_image
airbyte-ci connectors --name source-whisky-hunter migrate_to_base_image
airbyte-ci connectors --name source-wikipedia-pageviews migrate_to_base_image
airbyte-ci connectors --name source-woocommerce migrate_to_base_image
airbyte-ci connectors --name source-workable migrate_to_base_image
airbyte-ci connectors --name source-workramp migrate_to_base_image
airbyte-ci connectors --name source-wrike migrate_to_base_image
airbyte-ci connectors --name source-xero migrate_to_base_image
airbyte-ci connectors --name source-xkcd migrate_to_base_image
airbyte-ci connectors --name source-yahoo-finance-price migrate_to_base_image
airbyte-ci connectors --name source-yandex-metrica migrate_to_base_image
airbyte-ci connectors --name source-yotpo migrate_to_base_image
airbyte-ci connectors --name source-youtube-analytics migrate_to_base_image
airbyte-ci connectors --name source-zapier-supported-storage migrate_to_base_image
airbyte-ci connectors --name source-zendesk-sell migrate_to_base_image
airbyte-ci connectors --name source-zendesk-sunshine migrate_to_base_image
airbyte-ci connectors --name source-zenefits migrate_to_base_image
airbyte-ci connectors --name source-zenloop migrate_to_base_image
airbyte-ci connectors --name  migrate_to_base_image