#!/bin/bash

airbyte-ci connectors --name source-activecampaign migrate-to-poetry
airbyte-ci connectors --name source-aha migrate-to-poetry
airbyte-ci connectors --name source-aircall migrate-to-poetry
airbyte-ci connectors --name source-alpha-vantage migrate-to-poetry
airbyte-ci connectors --name source-apify-dataset migrate-to-poetry
airbyte-ci connectors --name source-appfollow migrate-to-poetry
airbyte-ci connectors --name source-apple-search-ads migrate-to-poetry
airbyte-ci connectors --name source-appsflyer migrate-to-poetry
airbyte-ci connectors --name source-asana migrate-to-poetry
airbyte-ci connectors --name source-ashby migrate-to-poetry
airbyte-ci connectors --name source-aws-cloudtrail migrate-to-poetry
airbyte-ci connectors --name source-babelforce migrate-to-poetry
airbyte-ci connectors --name source-bamboo-hr migrate-to-poetry
airbyte-ci connectors --name source-bigcommerce migrate-to-poetry
airbyte-ci connectors --name source-braintree migrate-to-poetry
airbyte-ci connectors --name source-braze migrate-to-poetry
airbyte-ci connectors --name source-breezometer migrate-to-poetry
airbyte-ci connectors --name source-callrail migrate-to-poetry
airbyte-ci connectors --name source-captain-data migrate-to-poetry
airbyte-ci connectors --name source-cart migrate-to-poetry
airbyte-ci connectors --name source-chargify migrate-to-poetry
airbyte-ci connectors --name source-chartmogul migrate-to-poetry
airbyte-ci connectors --name source-clickup-api migrate-to-poetry
airbyte-ci connectors --name source-clockify migrate-to-poetry
airbyte-ci connectors --name source-close-com migrate-to-poetry
airbyte-ci connectors --name source-coda migrate-to-poetry
airbyte-ci connectors --name source-coin-api migrate-to-poetry
airbyte-ci connectors --name source-coingecko-coins migrate-to-poetry
airbyte-ci connectors --name source-coinmarketcap migrate-to-poetry
airbyte-ci connectors --name source-commercetools migrate-to-poetry
airbyte-ci connectors --name source-configcat migrate-to-poetry
airbyte-ci connectors --name source-confluence migrate-to-poetry
airbyte-ci connectors --name source-convertkit migrate-to-poetry
airbyte-ci connectors --name source-copper migrate-to-poetry
airbyte-ci connectors --name source-customer-io migrate-to-poetry
airbyte-ci connectors --name source-datadog migrate-to-poetry
airbyte-ci connectors --name source-datascope migrate-to-poetry
airbyte-ci connectors --name source-delighted migrate-to-poetry
airbyte-ci connectors --name source-dixa migrate-to-poetry
airbyte-ci connectors --name source-dockerhub migrate-to-poetry
airbyte-ci connectors --name source-dremio migrate-to-poetry
airbyte-ci connectors --name source-drift migrate-to-poetry
airbyte-ci connectors --name source-emailoctopus migrate-to-poetry
airbyte-ci connectors --name source-everhour migrate-to-poetry
airbyte-ci connectors --name source-exchange-rates migrate-to-poetry
airbyte-ci connectors --name source-fastbill migrate-to-poetry
airbyte-ci connectors --name source-freshcaller migrate-to-poetry
airbyte-ci connectors --name source-freshsales migrate-to-poetry
airbyte-ci connectors --name source-freshservice migrate-to-poetry
airbyte-ci connectors --name source-fullstory migrate-to-poetry
airbyte-ci connectors --name source-gainsight-px migrate-to-poetry
airbyte-ci connectors --name source-genesys migrate-to-poetry
airbyte-ci connectors --name source-getlago migrate-to-poetry
airbyte-ci connectors --name source-glassfrog migrate-to-poetry
airbyte-ci connectors --name source-gocardless migrate-to-poetry
airbyte-ci connectors --name source-gong migrate-to-poetry
airbyte-ci connectors --name source-google-directory migrate-to-poetry
airbyte-ci connectors --name source-google-pagespeed-insights migrate-to-poetry
airbyte-ci connectors --name source-google-webfonts migrate-to-poetry
airbyte-ci connectors --name source-gutendex migrate-to-poetry
airbyte-ci connectors --name source-harness migrate-to-poetry
airbyte-ci connectors --name source-hellobaton migrate-to-poetry
airbyte-ci connectors --name source-hubplanner migrate-to-poetry
airbyte-ci connectors --name source-insightly migrate-to-poetry
airbyte-ci connectors --name source-instatus migrate-to-poetry
airbyte-ci connectors --name source-intruder migrate-to-poetry
airbyte-ci connectors --name source-ip2whois migrate-to-poetry
airbyte-ci connectors --name source-k6-cloud migrate-to-poetry
airbyte-ci connectors --name source-klarna migrate-to-poetry
airbyte-ci connectors --name source-klaus-api migrate-to-poetry
airbyte-ci connectors --name source-launchdarkly migrate-to-poetry
airbyte-ci connectors --name source-lemlist migrate-to-poetry
airbyte-ci connectors --name source-linkedin-pages migrate-to-poetry
airbyte-ci connectors --name source-lokalise migrate-to-poetry
airbyte-ci connectors --name source-looker migrate-to-poetry
airbyte-ci connectors --name source-mailerlite migrate-to-poetry
airbyte-ci connectors --name source-mailersend migrate-to-poetry
airbyte-ci connectors --name source-mailgun migrate-to-poetry
airbyte-ci connectors --name source-mailjet-mail migrate-to-poetry
airbyte-ci connectors --name source-mailjet-sms migrate-to-poetry
airbyte-ci connectors --name source-merge migrate-to-poetry
airbyte-ci connectors --name source-microsoft-teams migrate-to-poetry
airbyte-ci connectors --name source-my-hours migrate-to-poetry
airbyte-ci connectors --name source-n8n migrate-to-poetry
airbyte-ci connectors --name source-nasa migrate-to-poetry
airbyte-ci connectors --name source-news-api migrate-to-poetry
airbyte-ci connectors --name source-newsdata migrate-to-poetry
airbyte-ci connectors --name source-nytimes migrate-to-poetry
airbyte-ci connectors --name source-okta migrate-to-poetry
airbyte-ci connectors --name source-omnisend migrate-to-poetry
airbyte-ci connectors --name source-onesignal migrate-to-poetry
airbyte-ci connectors --name source-open-exchange-rates migrate-to-poetry
airbyte-ci connectors --name source-openweather migrate-to-poetry
airbyte-ci connectors --name source-opsgenie migrate-to-poetry
airbyte-ci connectors --name source-orbit migrate-to-poetry
airbyte-ci connectors --name source-oura migrate-to-poetry
airbyte-ci connectors --name source-outbrain-amplify migrate-to-poetry
airbyte-ci connectors --name source-outreach migrate-to-poetry
airbyte-ci connectors --name source-pagerduty migrate-to-poetry
airbyte-ci connectors --name source-pardot migrate-to-poetry
airbyte-ci connectors --name source-partnerstack migrate-to-poetry
airbyte-ci connectors --name source-paystack migrate-to-poetry
airbyte-ci connectors --name source-pendo migrate-to-poetry
airbyte-ci connectors --name source-persistiq migrate-to-poetry
airbyte-ci connectors --name source-pexels-api migrate-to-poetry
airbyte-ci connectors --name source-pipedrive migrate-to-poetry
airbyte-ci connectors --name source-pivotal-tracker migrate-to-poetry
airbyte-ci connectors --name source-plaid migrate-to-poetry
airbyte-ci connectors --name source-plausible migrate-to-poetry
airbyte-ci connectors --name source-pocket migrate-to-poetry
airbyte-ci connectors --name source-pokeapi migrate-to-poetry
airbyte-ci connectors --name source-polygon-stock-api migrate-to-poetry
airbyte-ci connectors --name source-posthog migrate-to-poetry
airbyte-ci connectors --name source-postmarkapp migrate-to-poetry
airbyte-ci connectors --name source-prestashop migrate-to-poetry
airbyte-ci connectors --name source-primetric migrate-to-poetry
airbyte-ci connectors --name source-public-apis migrate-to-poetry
airbyte-ci connectors --name source-punk-api migrate-to-poetry
airbyte-ci connectors --name source-pypi migrate-to-poetry
airbyte-ci connectors --name source-python-http-tutorial migrate-to-poetry
airbyte-ci connectors --name source-qonto migrate-to-poetry
airbyte-ci connectors --name source-qualaroo migrate-to-poetry
airbyte-ci connectors --name source-railz migrate-to-poetry
airbyte-ci connectors --name source-rd-station-marketing migrate-to-poetry
airbyte-ci connectors --name source-recreation migrate-to-poetry
airbyte-ci connectors --name source-recruitee migrate-to-poetry
airbyte-ci connectors --name source-reply-io migrate-to-poetry
airbyte-ci connectors --name source-retently migrate-to-poetry
airbyte-ci connectors --name source-ringcentral migrate-to-poetry
airbyte-ci connectors --name source-rki-covid migrate-to-poetry
airbyte-ci connectors --name source-rocket-chat migrate-to-poetry
airbyte-ci connectors --name source-rss migrate-to-poetry
airbyte-ci connectors --name source-salesloft migrate-to-poetry
airbyte-ci connectors --name source-sap-fieldglass migrate-to-poetry
airbyte-ci connectors --name source-secoda migrate-to-poetry
airbyte-ci connectors --name source-sendinblue migrate-to-poetry
airbyte-ci connectors --name source-senseforce migrate-to-poetry
airbyte-ci connectors --name source-serpstat migrate-to-poetry
airbyte-ci connectors --name source-shortio migrate-to-poetry
airbyte-ci connectors --name source-smaily migrate-to-poetry
airbyte-ci connectors --name source-smartengage migrate-to-poetry
airbyte-ci connectors --name source-sonar-cloud migrate-to-poetry
airbyte-ci connectors --name source-spacex-api migrate-to-poetry
airbyte-ci connectors --name source-square migrate-to-poetry
airbyte-ci connectors --name source-statuspage migrate-to-poetry
airbyte-ci connectors --name source-strava migrate-to-poetry
airbyte-ci connectors --name source-survey-sparrow migrate-to-poetry
airbyte-ci connectors --name source-tempo migrate-to-poetry
airbyte-ci connectors --name source-the-guardian-api migrate-to-poetry
airbyte-ci connectors --name source-timely migrate-to-poetry
airbyte-ci connectors --name source-tmdb migrate-to-poetry
airbyte-ci connectors --name source-toggl migrate-to-poetry
airbyte-ci connectors --name source-tplcentral migrate-to-poetry
airbyte-ci connectors --name source-trello migrate-to-poetry
airbyte-ci connectors --name source-trustpilot migrate-to-poetry
airbyte-ci connectors --name source-tvmaze-schedule migrate-to-poetry
airbyte-ci connectors --name source-twilio-taskrouter migrate-to-poetry
airbyte-ci connectors --name source-twitter migrate-to-poetry
airbyte-ci connectors --name source-tyntec-sms migrate-to-poetry
airbyte-ci connectors --name source-unleash migrate-to-poetry
airbyte-ci connectors --name source-vantage migrate-to-poetry
airbyte-ci connectors --name source-visma-economic migrate-to-poetry
airbyte-ci connectors --name source-vitally migrate-to-poetry
airbyte-ci connectors --name source-waiteraid migrate-to-poetry
airbyte-ci connectors --name source-weatherstack migrate-to-poetry
airbyte-ci connectors --name source-whisky-hunter migrate-to-poetry
airbyte-ci connectors --name source-wikipedia-pageviews migrate-to-poetry
airbyte-ci connectors --name source-woocommerce migrate-to-poetry
airbyte-ci connectors --name source-workable migrate-to-poetry
airbyte-ci connectors --name source-workramp migrate-to-poetry
airbyte-ci connectors --name source-wrike migrate-to-poetry
airbyte-ci connectors --name source-xero migrate-to-poetry
airbyte-ci connectors --name source-xkcd migrate-to-poetry
airbyte-ci connectors --name source-yahoo-finance-price migrate-to-poetry
airbyte-ci connectors --name source-yandex-metrica migrate-to-poetry
airbyte-ci connectors --name source-yotpo migrate-to-poetry
airbyte-ci connectors --name source-youtube-analytics migrate-to-poetry
airbyte-ci connectors --name source-zapier-supported-storage migrate-to-poetry
airbyte-ci connectors --name source-zendesk-sell migrate-to-poetry
airbyte-ci connectors --name source-zendesk-sunshine migrate-to-poetry
airbyte-ci connectors --name source-zenefits migrate-to-poetry
airbyte-ci connectors --name source-zenloop migrate-to-poetry