Table "media" {
    "business_account_id" string
    "page_id" string
    "caption" string
    "comments_count" integer
    "id" string [pk]
    "ig_id" string
    "is_comment_enabled" boolean
    "like_count" integer
    "media_type" string
    "media_product_type" string
    "media_url" string
    "owner" object
    "permalink" string
    "shortcode" string
    "thumbnail_url" string
    "timestamp" string
    "username" string
    "children" array
}

Table "media_insights" {
    "business_account_id" string
    "page_id" string
    "id" string [pk]
    "ig_reels_avg_watch_time" number
    "ig_reels_video_view_total_time" number
    "impressions" integer
    "reach" integer
    "saved" integer
    "video_views" integer
    "comments" integer
    "likes" integer
    "shares" integer
    "total_interactions" integer
    "plays" integer
    "ig_reels_aggregated_all_plays_count" integer
    "clips_replays_count" integer
    "follows" integer
    "profile_visits" integer
}

Table "users" {
    "page_id" string
    "id" string [pk]
    "biography" string
    "ig_id" integer
    "followers_count" integer
    "follows_count" integer
    "media_count" integer
    "name" string
    "profile_picture_url" string
    "username" string
    "website" string
}

Table "user_lifetime_insights" {
    "page_id" string
    "business_account_id" string
    "breakdown" string
    "metric" string
    "value" object

    indexes {
        (business_account_id, breakdown) [pk]
    }
}

Table "stories" {
    "business_account_id" string
    "page_id" string
    "caption" string
    "id" string [pk]
    "ig_id" string
    "like_count" integer
    "media_type" string
    "media_product_type" string
    "media_url" string
    "owner" object
    "permalink" string
    "shortcode" string
    "thumbnail_url" string
    "timestamp" string
    "username" string
}

Table "story_insights" {
    "business_account_id" string
    "page_id" string
    "id" string
    "impressions" integer
    "reach" integer
    "replies" integer
    "follows" integer
    "profile_visits" integer
    "shares" integer
    "total_interactions" integer
}

Table "Api" {
    "account" object
    "id" string [pk]
}

Table "user_insights" {
    "page_id" string
    "business_account_id" string
    "date" string
    "follower_count" integer
    "get_directions_clicks" integer
    "impressions" integer
    "phone_call_clicks" integer
    "profile_views" integer
    "reach" integer
    "text_message_clicks" integer
    "website_clicks" integer
    "impressions_week" integer
    "reach_week" integer
    "impressions_days_28" integer
    "reach_days_28" integer
    "online_followers" object
    "email_contacts" integer

    indexes {
        (business_account_id, date) [pk]
    }
}

Ref {
    "media"."page_id" <> "users"."page_id"
}

Ref {
    "media_insights"."page_id" <> "users"."page_id"
}

Ref {
    "media_insights"."id" <> "media"."id"
}

Ref {
    "user_lifetime_insights"."page_id" <> "users"."page_id"
}

Ref {
    "stories"."page_id" <> "users"."page_id"
}

Ref {
    "story_insights"."page_id" <> "users"."page_id"
}

Ref {
    "user_insights"."page_id" <> "users"."page_id"
}