#
# Copyright (c) 2022 Airbyte, Inc., all rights reserved.
#

from typing import Union

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

# coding: utf-8

"""
    Connector Builder Server API

    Connector Builder Server API 

    The version of the OpenAPI document: 1.0.0
    Contact: contact@airbyte.io
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from connector_builder.impl.default_api import DefaultApiImpl
from connector_builder.generated.apis.default_api_interface import initialize_router

app = FastAPI(
    title="Connector Builder Server API",
    description="Connector Builder Server API ",
    version="1.0.0",
)

app.include_router(initialize_router(DefaultApiImpl()))
