from source_kyve.util import CustomResourceSchemaLoader


def test_custom_loader():
    custom_loader = CustomResourceSchemaLoader("source_kyve")
    schema = custom_loader.get_schema("evm/block")
    assert schema == {'$schema': 'http://json-schema.org/draft-04/schema#',
                      'properties': {'_difficulty': {'properties': {'hex': {'type': 'string'},
                                                                    'type': {'type': 'string'}},
                                                     'required': ['hex', 'type'],
                                                     'type': 'object'},
                                     'difficulty': {'type': 'integer'},
                                     'extraData': {'type': 'string'},
                                     'gasLimit': {'properties': {'hex': {'type': 'string'},
                                                                 'type': {'type': 'string'}},
                                                  'required': ['hex', 'type'],
                                                  'type': 'object'},
                                     'gasUsed': {'properties': {'hex': {'type': 'string'},
                                                                'type': {'type': 'string'}},
                                                 'required': ['hex', 'type'],
                                                 'type': 'object'},
                                     'hash': {'type': 'string'},
                                     'miner': {'type': 'string'},
                                     'number': {'type': 'integer'},
                                     'parentHash': {'type': 'string'},
                                     'timestamp': {'type': 'integer'},
                                     'transactions': {'items': {'$schema': 'http://json-schema.org/draft-04/schema#',
                                                                'properties': {'accessList': {'type': 'null'},
                                                                               'blockHash': {'type': 'string'},
                                                                               'blockNumber': {'type': 'integer'},
                                                                               'chainId': {'type': 'integer'},
                                                                               'creates': {'type': ['null', 'string']},
                                                                               'data': {'type': 'string'},
                                                                               'from': {'type': 'string'},
                                                                               'gasLimit': {'properties': {'hex': {'type': 'string'},
                                                                                                           'type': {'type': 'string'}},
                                                                                            'required': ['hex',
                                                                                                         'type'],
                                                                                            'type': 'object'},
                                                                               'gasPrice': {'properties': {'hex': {'type': 'string'},
                                                                                                           'type': {'type': 'string'}},
                                                                                            'required': ['hex',
                                                                                                         'type'],
                                                                                            'type': 'object'},
                                                                               'hash': {'type': 'string'},
                                                                               'nonce': {'type': 'integer'},
                                                                               'r': {'type': 'string'},
                                                                               'raw': {'type': 'string'},
                                                                               's': {'type': 'string'},
                                                                               'to': {'type': ['string', 'null']},
                                                                               'transactionIndex': {'type': 'integer'},
                                                                               'type': {'type': 'integer'},
                                                                               'v': {'type': 'integer'},
                                                                               'value': {'properties': {'hex': {'type': 'string'},
                                                                                                        'type': {'type': 'string'}},
                                                                                         'required': ['hex',
                                                                                                      'type'],
                                                                                         'type': 'object'}},
                                                                'required': ['r',
                                                                             's',
                                                                             'v',
                                                                             'to',
                                                                             'data',
                                                                             'from',
                                                                             'hash',
                                                                             'type',
                                                                             'nonce',
                                                                             'value',
                                                                             'chainId',
                                                                             'creates',
                                                                             'gasLimit',
                                                                             'gasPrice',
                                                                             'blockHash',
                                                                             'accessList',
                                                                             'blockNumber',
                                                                             'transactionIndex'],
                                                                'type': 'object'},
                                                      'type': 'array'}},
                      'required': ['hash',
                                   'miner',
                                   'number',
                                   'gasUsed',
                                   'gasLimit',
                                   'extraData',
                                   'timestamp',
                                   'difficulty',
                                   'parentHash',
                                   '_difficulty',
                                   'transactions'],
                      'type': 'object'}
