#
# Copyright (c) 2022 Airbyte, Inc., all rights reserved.
#

# This order matters
main_fields = (
    "date",
    "af_prt",
    "media_source",
    "campaign",
    "impressions",
    "clicks",
    "click_through_rate",
    "installs",
    "conversion_rate",
    "sessions",
    "loyal_users",
    "loyal_users_rate",
    "total_revenue",
    "total_cost",
    "return_on_investment",
    "average_revenue_per_user",
    "average_ecpi",
    "account_login_unique_users",
    "account_login_event_counter",
    "account_login_sales",
    "af_complete_registration_unique_users",
    "af_complete_registration_event_counter",
    "af_complete_registration_sales",
    "af_purchase_registration_unique_users",
    "af_purchase_registration_event_counter",
    "af_purchase_registration_sales",
    "checkout_success_unique_users",
    "checkout_success_event_counter",
    "checkout_success_sales",
    "create_product_complete_unique_users",
    "create_product_complete_event_counter",
    "create_product_complete_sales",
    "init_appsflyer_id_unique_users",
    "init_appsflyer_id_event_counter",
    "init_appsflyer_id_sales",
    "pay_premium_pkg_unique_users",
    "pay_premium_pkg_event_counter",
    "pay_premium_pkg_sales",
)
