#
# Copyright (c) 2022 Airbyte, Inc., all rights reserved.
#

# This order matters
additional_fields = (
    "custom_data",
    "network_account_id",
    "install_app_store",
    "contributor1_match_type",
    "contributor2_match_type",
    "contributor3_match_type",
    "match_type",
    "gp_referrer",
    "gp_click_time",
    "gp_install_begin",
    "gp_broadcast_referrer",
    "keyword_match_type",
    "keyword_id",
    "amazon_aid",
    "device_category",
    "device_model",
    "device_download_time",
    "deeplink_url",
    "oaid",
    "is_lat",
    "store_reinstall",
    "placement",
    "mediation_network",
    "segment",
    "ad_unit",
    "monetization_network",
    "impressions",
    "blocked_reason",
    "blocked_reason_value",
    "blocked_reason_rule",
    "blocked_sub_reason",
    "rejected_reason",
    "rejected_reason_value",
)
