

  create  table SYSTEM.CONFLICT_STREAM_NAME_CONFLICT_STREAM_NAME_CONFLICT_STREAM_NAME__dbt_tmp
  
  as
    
-- Final base SQL model
select
    AIRBYTE_CONFLICT_STREAM_NAME_2_HASHID,
    GROUPS,
    airbyte_emitted_at,
    AIRBYTE_CONFLICT_STREAM_NAME_3_HASHID
from SYSTEM.CONFLICT_STREAM_NAME_CONFLICT_STREAM_NAME_CONFLICT_STREAM_NAME_AB3
-- CONFLICT_STREAM_NAME at conflict_stream_name/conflict_stream_name/conflict_stream_name from SYSTEM.CONFLICT_STREAM_NAME_CONFLICT_STREAM_NAME