

  create  table SYSTEM.CONFLICT_STREAM_SCALAR__dbt_tmp
  
  as
    
-- Final base SQL model
select
    ID,
    CONFLICT_STREAM_SCALAR,
    airbyte_emitted_at,
    AIRBYTE_CONFLICT_STREAM_SCALAR_HASHID
from SYSTEM.CONFLICT_STREAM_SCALAR_AB3
-- CONFLICT_STREAM_SCALAR from "SYSTEM"."AIRBYTE_RAW_CONFLICT_STREAM_SCALAR"