FROM airbyte/base-python-test:dev

RUN apt-get update && apt-get install -y \
    bash \
    && rm -rf /var/lib/apt/lists/*

ENV CODE_PATH="standardtest"
ENV AIRBYTE_TEST_MODULE="standardtest"
ENV AIRBYTE_TEST_PATH="GoogleAnalyticsStandardSourceTest"
ENV AIRBYTE_TEST_CASE=true

LABEL io.airbyte.version=0.1.0
LABEL io.airbyte.name=airbyte/source-googleanalytics-singer-standard-test

WORKDIR /airbyte/integration_code
COPY $CODE_PATH ./$CODE_PATH

# copy all resources to the code path.
COPY secrets/config.json ./$CODE_PATH/config.json
COPY secrets/tracker.txt ./$CODE_PATH/tracker.txt
COPY sample_files/test_catalog.json ./$CODE_PATH/test_catalog.json
COPY source_googleanalytics_singer/spec.json ./$CODE_PATH/spec.json

COPY setup.py ./
RUN pip install ".[standardtest]"

WORKDIR /airbyte
