/*
 * Copyright (c) 2024 Airbyte, Inc., all rights reserved.
 */

import io.airbyte.cdk.command.ConfigurationSpecification
import io.airbyte.cdk.command.ValidatedJsonUtils
import io.airbyte.cdk.load.command.DestinationCatalog
import io.airbyte.cdk.load.command.DestinationStream
import io.airbyte.cdk.load.command.NamespaceMapper
import io.airbyte.cdk.load.command.Update
import io.airbyte.cdk.load.data.FieldType
import io.airbyte.cdk.load.data.ObjectType
import io.airbyte.cdk.load.data.StringType
import io.airbyte.cdk.load.message.InputRecord
import io.airbyte.cdk.load.message.InputStreamCheckpoint
import io.airbyte.cdk.load.message.Meta.Change
import io.airbyte.cdk.load.test.util.DestinationCleaner
import io.airbyte.cdk.load.test.util.DestinationDataDumper
import io.airbyte.cdk.load.test.util.OutputRecord
import io.airbyte.cdk.load.write.BasicFunctionalityIntegrationTest
import io.airbyte.cdk.load.write.SchematizedNestedValueBehavior
import io.airbyte.cdk.load.write.UnionBehavior
import io.airbyte.cdk.load.write.Untyped
import io.airbyte.integrations.destination.salesforce.SalesforceSpecification
import io.airbyte.protocol.models.v0.AirbyteMessage
import io.airbyte.protocol.models.v0.AirbyteRecordMessageMetaChange
import java.nio.file.Files
import java.nio.file.Path
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertAll

class SalesforceDataDumper : DestinationDataDumper {
    override fun dumpRecords(
        spec: ConfigurationSpecification,
        stream: DestinationStream
    ): List<OutputRecord> {
        TODO("Not yet implemented")
    }

    override fun dumpFile(
        spec: ConfigurationSpecification,
        stream: DestinationStream
    ): Map<String, String> {
        TODO("Not yet implemented")
    }
}

object SalesforceDataCleaner : DestinationCleaner {
    override fun cleanup() {}
}

class SalesforceWriterTest() :
    BasicFunctionalityIntegrationTest(
        configContents = Files.readString(Path.of("secrets/config.json")),
        configSpecClass = SalesforceSpecification::class.java,
        dataDumper = SalesforceDataDumper(),
        destinationCleaner = SalesforceDataCleaner,
        commitDataIncrementally = true,
        allTypesBehavior = Untyped,
        verifyDataWriting = false,
        isStreamSchemaRetroactive = false,
        dedupBehavior = null,
        stringifySchemalessObjects = true,
        schematizedArrayBehavior = SchematizedNestedValueBehavior.STRINGIFY,
        schematizedObjectBehavior = SchematizedNestedValueBehavior.STRINGIFY,
        unionBehavior = UnionBehavior.STRINGIFY,
        supportFileTransfer = false,
    ) {
    private val accountStream: DestinationStream =
        DestinationStream(
            randomizedNamespace,
            "test_stream_account",
            Update,
            ObjectType(
                linkedMapOf(
                    "Id" to FieldType(StringType, nullable = true),
                    "Description" to FieldType(StringType, nullable = true)
                )
            ),
            generationId = 0,
            minimumGenerationId = 0,
            syncId = 42,
            destinationObjectName = "Account",
            namespaceMapper = NamespaceMapper()
        )

    private val contactStream: DestinationStream =
        DestinationStream(
            randomizedNamespace,
            "test_stream_contact",
            Update,
            ObjectType(
                linkedMapOf(
                    "Id" to FieldType(StringType, nullable = true),
                    "Title" to FieldType(StringType, nullable = true)
                )
            ),
            generationId = 0,
            minimumGenerationId = 0,
            syncId = 42,
            destinationObjectName = "Contact",
            namespaceMapper = NamespaceMapper()
        )

    fun accountRecord(id: String) =
        InputRecord(
            stream = accountStream,
            data =
                """{"Id": "$id", "Description": "This description was generated by destination-salesforce integration tests"}""",
            emittedAtMs = 1234,
        )

    fun contactRecord(id: String) =
        InputRecord(
            stream = contactStream,
            data =
                """{"Id": "$id", "Title": "This title was generated by destination-salesforce integration tests"}""",
            emittedAtMs = 1234,
        )

    @Test
    override fun testBasicWrite() {
        val messages =
            runSync(
                updatedConfig,
                DestinationCatalog(listOf(accountStream, contactStream)),
                listOf(
                    accountRecord("001cW00000DQthLQAT"),
                    contactRecord("003cW00000E387RQAR"),
                    contactRecord("003cW00000E38FVQAZ"),
                    accountRecord("001cW000009bYVSQA2"),
                    accountRecord("001cW000009bcE1QAI"),
                    contactRecord("003cW00000E37WMQAZ"),
                    accountRecord("001cW000009bc9BQAQ"),
                    accountRecord("001cW00000DQpnSQAT"),
                    contactRecord("003cW00000E38CHQAZ"),
                    accountRecord("001cW000009bVUKQA2"),
                    accountRecord("001cW000009bXeDQAU"),
                    InputStreamCheckpoint(
                        unmappedNamespace = accountStream.mappedDescriptor.namespace,
                        unmappedName = accountStream.mappedDescriptor.name,
                        blob = """{"foo": "bar"}""",
                        sourceRecordCount = 7,
                    ),
                    InputStreamCheckpoint(
                        unmappedNamespace = contactStream.mappedDescriptor.namespace,
                        unmappedName = contactStream.mappedDescriptor.name,
                        blob = """{"foo": "bar"}""",
                        sourceRecordCount = 4,
                    )
                ),
            )

        val stateMessages = messages.filter { it.type == AirbyteMessage.Type.STATE }
        assertAll(
            {
                assertEquals(
                    2,
                    stateMessages.size,
                    "Expected to receive exactly two (one for each stream) state message, got ${stateMessages.size} ($stateMessages)"
                )
            },
            {
                if (verifyDataWriting) {
                    dumpAndDiffRecords(
                        ValidatedJsonUtils.parseOne(configSpecClass, updatedConfig),
                        listOf(
                            OutputRecord(
                                extractedAt = 1234,
                                generationId = 0,
                                data = mapOf("id" to 5678),
                                airbyteMeta =
                                    OutputRecord.Meta(
                                        changes =
                                            mutableListOf(
                                                Change(
                                                    field = "foo",
                                                    change =
                                                        AirbyteRecordMessageMetaChange.Change
                                                            .NULLED,
                                                    reason =
                                                        AirbyteRecordMessageMetaChange.Reason
                                                            .SOURCE_FIELD_SIZE_LIMITATION
                                                )
                                            ),
                                        syncId = 42
                                    )
                            )
                        ),
                        accountStream,
                        primaryKey = listOf(listOf("id")),
                        cursor = null,
                    )
                }
            },
        )
    }
}
