
FROM airbyte/base-python-test:dev

RUN apt-get update && apt-get install -y \
    bash \
    && rm -rf /var/lib/apt/lists/*

ENV CODE_PATH="standardtest"
ENV AIRBYTE_TEST_MODULE="standardtest"
ENV AIRBYTE_TEST_PATH="HubspotStandardSourceTest"

LABEL io.airbyte.version=0.1.0
LABEL io.airbyte.name=airbyte/source-hubspot-singer-standard-test

WORKDIR /airbyte/integration_code
COPY secrets ./$CODE_PATH
COPY resources ./$CODE_PATH
COPY resourcesstandardtest ./$CODE_PATH
COPY $CODE_PATH ./$CODE_PATH
COPY setup.py ./
RUN pip install ".[standardtest]"

WORKDIR /airbyte

