[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "source-apple-search-ads-tests"
version = "0.0.1"
description = "Unit tests for source-apple-search-ads"
authors = ["Airbyte <contact@airbyte.io>"]

[tool.poetry.dependencies]
python = "^3.10,<3.13"
airbyte-cdk = "^7"
pytest = "^8"
jsonschema = "^4"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:This class is experimental*",
]
