#
# Copyright (c) 2023 Airbyte, Inc., all rights reserved.
#


import json
from datetime import datetime
from typing import Dict, Generator

from airbyte_cdk.logger import AirbyteLogger
from airbyte_cdk.models import (
    AirbyteCatalog,
    AirbyteConnectionStatus,
    AirbyteMessage,
    AirbyteStateMessage,
    AirbyteRecordMessage,
    ConfiguredAirbyteCatalog,
    Status,
    Type,
    SyncMode,
)
from airbyte_cdk.sources import Source
from .client import Client


class SourceKintone(Source):
    def check(self, logger: AirbyteLogger, config: json) -> AirbyteConnectionStatus:
        """
        Tests if the input configuration can be used to successfully connect to the integration
            e.g: if a provided Stripe API token can be used to connect to the Stripe API.

        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json is as specified in
        the properties of the spec.yaml file

        :return: AirbyteConnectionStatus indicating a Success or Failure
        """
        client = Client(config, logger)
        for app_id in config.get("app_ids"):
            if not client.get_app(app_id):
                return AirbyteConnectionStatus(
                    status=Status.FAILED,
                    message=f"app name is not found of app_id={app_id}.\n"
                    f"https://jp.cybozu.help/k/en/user/app_settings/app_othersettings/appcode.html"
                )

        return AirbyteConnectionStatus(status=Status.SUCCEEDED)

    def discover(self, logger: AirbyteLogger, config: json) -> AirbyteCatalog:
        """
        Returns an AirbyteCatalog representing the available streams and fields in this integration.
        For example, given valid credentials to a Postgres database,
        returns an Airbyte catalog where each postgres table is a stream, and each table column is a field.

        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json is as specified in
        the properties of the spec.yaml file

        :return: AirbyteCatalog is an object describing a list of all available streams in this source.
            A stream is an AirbyteStream object that includes:
            - its stream name (or table name in the case of Postgres)
            - json_schema providing the specifications of expected schema for this stream (a list of columns described
            by their names and types)
        """
        streams = []

        client = Client(config, logger)
        for app_id in config.get("app_ids"):
            stream = client.get_stream(app_id)
            if stream:
                streams.append(stream)

        return AirbyteCatalog(streams=streams)

    def read(
        self, logger: AirbyteLogger, config: json, catalog: ConfiguredAirbyteCatalog, state: Dict[str, any]
    ) -> Generator[AirbyteMessage, None, None]:
        """
        Returns a generator of the AirbyteMessages generated by reading the source with the given configuration,
        catalog, and state.

        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json is as specified in
            the properties of the spec.yaml file
        :param catalog: The input catalog is a ConfiguredAirbyteCatalog which is almost the same as AirbyteCatalog
            returned by discover(), but
        in addition, it's been configured in the UI! For each particular stream and field, there may have been provided
        with extra modifications such as: filtering streams and/or columns out, renaming some entities, etc
        :param state: When a Airbyte reads data from a source, it might need to keep a checkpoint cursor to resume
            replication in the future from that saved checkpoint.
            This is the object that is provided with state from previous runs and avoid replicating the entire set of
            data everytime.

        :return: A generator that produces a stream of AirbyteRecordMessage contained in AirbyteMessage object.
        """
        logger.info(f"state: {state}")

        client = Client(config, logger)
        apps = {}
        for app_id in config.get("app_ids"):
            app = client.get_app(app_id)
            app_name = app.get("name")
            apps[app_name] = app

        cursor_field, cursor_value = None, None
        for configured_stream in catalog.streams:
            stream_name = configured_stream.stream.name
            app = apps.get(stream_name)
            if not app:
                logger.info(f"stream '{stream_name}' app code is not found")
                continue

            if configured_stream.sync_mode == SyncMode.full_refresh:
                logger.info(
                    f"syncing stream '{stream_name}' with full_refresh")

            elif configured_stream.sync_mode == SyncMode.incremental:
                logger.info(f"syncing stream '{stream_name}' with incremental")
                if stream_name not in state:
                    state[stream_name] = {}

                cursor_field = configured_stream.cursor_field[0]
                cursor_value = state[stream_name].get(cursor_field, None)

            else:
                logger.error(
                    f"could not sync stream '{configured_stream.stream.name}', invalid sync_mode: {configured_stream.sync_mode}")

            logger.info(f"app: '{app}'")
            records = client.get_app_records(app["appId"], cursor_field, cursor_value)
            for record in records:
                cursor_value = record.get(cursor_field, cursor_value)
                yield AirbyteMessage(
                    type=Type.RECORD,
                    record=AirbyteRecordMessage(
                        stream=app["name"],
                        data=record,
                        emitted_at=self._find_emitted_at(),
                    ))
            state[stream_name][cursor_field] = cursor_value

        yield AirbyteMessage(
            type=Type.STATE,
            state=AirbyteStateMessage(
                data=state,
                emitted_at=self._find_emitted_at(),
            ),
        )

        logger.info(f"Finished syncing {self.__class__.__name__}")


    def _find_emitted_at(self) -> int:
        # Returns now, in microseconds. This is a seperate function, so that it is easy
        # to replace in unit tests.
        return int(datetime.now().timestamp()) * 1000
