plugins {
    id 'application'
    id 'airbyte-java-connector'
}

airbyteJavaConnector {
    cdkVersionRequired = '0.40.3'
    features = ['db-destinations']
    useLocalCdk = false
}

java {
    compileJava {
        options.compilerArgs.remove("-Werror")
    }
}

airbyteJavaConnector.addCdkDependencies()

application {
    mainClass = 'io.airbyte.integrations.destination.doris.DorisDestination'
}

dependencies {
    implementation 'org.apache.commons:commons-csv:1.4'
    implementation group: 'mysql', name: 'mysql-connector-java', version: '8.0.16'
    implementation 'org.apache.httpcomponents:httpclient:4.5.14'
    implementation 'commons-codec:commons-codec:1.16.0'
}
