STREAMS = {
    "account_performance_report": [
        ['customer.currency_code', 'customer.descriptive_name', 'metrics.average_cost', 'metrics.average_cpc',
         'metrics.average_cpe', 'metrics.average_cpm', 'metrics.average_cpv', 'metrics.conversions_value',
         'metrics.conversions', 'metrics.cost_micros', 'metrics.cost_per_all_conversions',
         'metrics.cost_per_conversion', 'metrics.cross_device_conversions', 'metrics.ctr', 'segments.date'],
        ['customer.currency_code', 'customer.descriptive_name', 'metrics.average_cost',
         'metrics.average_cpc',
         'metrics.average_cpe', 'metrics.average_cpm', 'metrics.average_cpv',
         'metrics.conversions_value',
         'metrics.conversions', 'metrics.cost_micros', 'metrics.cost_per_all_conversions',
         'metrics.cost_per_conversion', 'metrics.cross_device_conversions', 'metrics.ctr',
         'segments.date']
    ],
    "display_topics_performance":
        ["customer.currency_code",
         "customer.descriptive_name",
         "customer.time_zone",
         "metrics.active_view_cpm", "metrics.active_view_ctr",
         "metrics.active_view_impressions",
         "metrics.active_view_measurability",
         "metrics.active_view_measurable_cost_micros",
         "metrics.active_view_measurable_impressions",
         "metrics.active_view_viewability",
         "ad_group.id",
         "ad_group.name",
         "ad_group.status",
         "segments.ad_network_type",
         "metrics.all_conversions_from_interactions_rate",
         "metrics.all_conversions_value",
         "metrics.all_conversions",
         "metrics.average_cost",
         "metrics.average_cpc",
         "metrics.average_cpe",
         "metrics.average_cpm",
         "metrics.average_cpv",
         "ad_group.base_ad_group",
         "campaign.base_campaign",
         "ad_group_criterion.bid_modifier",
         "campaign.bidding_strategy",
         "campaign.bidding_strategy_type",
         "campaign.id",
         "campaign.name",
         "campaign.status",
         "metrics.clicks",
         "metrics.conversions_from_interactions_rate",
         "metrics.conversions_value",
         "metrics.conversions",
         "metrics.cost_micros",
         "metrics.cost_per_all_conversions",
         "metrics.cost_per_conversion",
         "ad_group_criterion.effective_cpc_bid_micros",
         "ad_group_criterion.effective_cpc_bid_source",
         "ad_group_criterion.effective_cpm_bid_micros",
         "ad_group_criterion.effective_cpm_bid_source",
         "ad_group_criterion.topic.path",
         "metrics.cross_device_conversions",
         "metrics.ctr",
         "segments.date",
         "segments.day_of_week",
         "segments.device",
         "metrics.engagement_rate",
         "metrics.engagements",
         "customer.id",
         "ad_group_criterion.final_mobile_urls",
         "ad_group_criterion.final_urls",
         "metrics.gmail_forwards",
         "metrics.gmail_saves",
         "metrics.gmail_secondary_clicks",
         "ad_group_criterion.criterion_id",
         "metrics.impressions",
         "metrics.interaction_rate",
         "metrics.interaction_event_types",
         "metrics.interactions",
         "ad_group_criterion.negative",
         "ad_group.targeting_setting.target_restrictions",
         "segments.month",
         "segments.quarter",
         "ad_group_criterion.status",
         "ad_group_criterion.tracking_url_template",
         "ad_group_criterion.url_custom_parameters",
         "metrics.value_per_all_conversions",
         "metrics.value_per_conversion",
         "ad_group_criterion.topic.topic_constant",
         "metrics.video_quartile_p100_rate",
         "metrics.video_quartile_p25_rate",
         "metrics.video_quartile_p50_rate",
         "metrics.video_quartile_p75_rate",
         "metrics.video_view_rate",
         "metrics.video_views",
         "metrics.view_through_conversions",
         "segments.week",
         "segments.year"

         ],
    "display_keyword_performance":
        ['customer.currency_code', 'customer.descriptive_name', 'customer.time_zone', 'metrics.active_view_cpm',
         'metrics.active_view_ctr', 'metrics.active_view_impressions', 'metrics.active_view_measurability',
         'metrics.active_view_measurable_cost_micros', 'metrics.active_view_measurable_impressions',
         'metrics.active_view_viewability', 'ad_group.id', 'ad_group.name', 'ad_group.status',
         'segments.ad_network_type', 'metrics.all_conversions_from_interactions_rate', 'metrics.all_conversions_value',
         'metrics.all_conversions', 'metrics.average_cost', 'metrics.average_cpc', 'metrics.average_cpe',
         'metrics.average_cpm', 'metrics.average_cpv', 'ad_group.base_ad_group', 'campaign.base_campaign',
         'campaign.bidding_strategy',
         'campaign.bidding_strategy_type', 'campaign.id', 'campaign.name', 'campaign.status',
         'metrics.clicks',
         'metrics.conversions_from_interactions_rate',
         'metrics.conversions_value',
         'metrics.conversions', 'metrics.cost_micros', 'metrics.cost_per_all_conversions',
         'metrics.cost_per_conversion', 'ad_group_criterion.effective_cpc_bid_micros',
         'ad_group_criterion.effective_cpc_bid_source', 'ad_group_criterion.effective_cpm_bid_micros',
         'ad_group_criterion.effective_cpm_bid_source', 'ad_group_criterion.effective_cpv_bid_micros',
         'ad_group_criterion.effective_cpv_bid_source', 'ad_group_criterion.keyword.text',
         'metrics.cross_device_conversions', 'metrics.ctr', 'customer.descriptive_name', 'segments.date',
         'segments.day_of_week', 'segments.device', 'metrics.engagement_rate', 'metrics.engagements',
         'customer.id', 'ad_group_criterion.final_mobile_urls',
         'ad_group_criterion.final_urls', 'metrics.gmail_forwards', 'metrics.gmail_saves',
         'metrics.gmail_secondary_clicks', 'ad_group_criterion.criterion_id', 'metrics.impressions',
         'metrics.interaction_rate', 'metrics.interaction_event_types', 'metrics.interactions',
         'ad_group_criterion.negative', 'ad_group.targeting_setting.target_restrictions', 'segments.month',
         'segments.quarter', 'ad_group_criterion.status',
         'ad_group_criterion.tracking_url_template', 'ad_group_criterion.url_custom_parameters',
         'metrics.value_per_all_conversions', 'metrics.value_per_conversion', 'metrics.video_quartile_p100_rate',
         'metrics.video_quartile_p25_rate', 'metrics.video_quartile_p50_rate', 'metrics.video_quartile_p75_rate',
         'metrics.video_view_rate', 'metrics.video_views', 'metrics.view_through_conversions', 'segments.week',
         'segments.year'],
    "shopping_performance": ['customer.descriptive_name', 'ad_group.id', 'ad_group.name', 'ad_group.status',
                             'segments.ad_network_type', 'segments.product_aggregator_id',
                             'metrics.all_conversions_from_interactions_rate', 'metrics.all_conversions_value',
                             'metrics.all_conversions',
                             'metrics.average_cpc', 'segments.product_brand', 'campaign.id', 'campaign.name',
                             'campaign.status',
                             'segments.product_bidding_category_level1', 'segments.product_bidding_category_level2',
                             'segments.product_bidding_category_level3', 'segments.product_bidding_category_level4',
                             'segments.product_bidding_category_level5', 'segments.product_channel',
                             'segments.product_channel_exclusivity', 'segments.click_type', 'metrics.clicks',
                             'metrics.conversions_from_interactions_rate',
                             'metrics.conversions_value',
                             'metrics.conversions', 'metrics.cost_micros', 'metrics.cost_per_all_conversions',
                             'metrics.cost_per_conversion', 'segments.product_country',
                             'metrics.cross_device_conversions', 'metrics.ctr',
                             'segments.product_custom_attribute0', 'segments.product_custom_attribute1',
                             'segments.product_custom_attribute2', 'segments.product_custom_attribute3',
                             'segments.product_custom_attribute4', 'segments.date',
                             'segments.day_of_week', 'segments.device',
                             'customer.id', 'metrics.impressions', 'segments.product_language',
                             'segments.product_merchant_id', 'segments.month', 'segments.product_item_id',
                             'segments.product_condition',
                             'segments.product_title', 'segments.product_type_l1', 'segments.product_type_l2',
                             'segments.product_type_l3',
                             'segments.product_type_l4', 'segments.product_type_l5', 'segments.quarter',
                             'segments.product_store_id', 'metrics.value_per_all_conversions',
                             'metrics.value_per_conversion', 'segments.week', 'segments.year'
                             ]
}
