-- database
 CREATE
    DATABASE airbyte;

\connect airbyte;

-- extensions
 CREATE
    EXTENSION IF NOT EXISTS "uuid-ossp";

-- types
 CREATE
    TYPE CONFIG_TYPE AS ENUM(
        'STANDARD_WORKSPACE',
        'STANDARD_SOURCE_DEFINITION',
        'SOURCE_CONNECTION',
        'STANDARD_DESTINATION_DEFINITION',
        'DESTINATION_CONNECTION',
        'STANDARD_SYNC',
        'STANDARD_SYNC_OPERATION',
        'STANDARD_SYNC_SUMMARY',
        'STANDARD_SYNC_INPUT',
        'NORMALIZATION_INPUT',
        'OPERATOR_DBT_INPUT',
        'STANDARD_SYNC_OUTPUT',
        'REPLICATION_OUTPUT',
        'STATE'
    );

-- tables
 CREATE
    TABLE
        AIRBYTE_CONFIGS(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            config_id VARCHAR(36) NOT NULL DEFAULT uuid_generate_v4(),
            config_type CONFIG_TYPE NOT NULL,
            config_blob JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

-- indices
 CREATE
    UNIQUE INDEX airbyte_configs_idx ON
    AIRBYTE_CONFIGS(
        config_type,
        config_id
    );

-- entries
 INSERT
    INTO
        AIRBYTE_CONFIGS
    VALUES(
        'server_uuid',
        uuid_generate_v4()
    );

-- grants
 GRANT ALL ON
DATABASE airbyte TO docker;
