connector_image: airbyte/destination-starrocks:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: "destination_starrocks/spec.json"
  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
      - config_path: "integration_tests/invalid_config.json"
        status: "failed"
