begin;
    
        
        
    

    

    merge into "AIRBYTE_DATABASE".TEST_NORMALIZATION."UNNEST_ALIAS" as DBT_INTERNAL_DEST
        using "AIRBYTE_DATABASE".TEST_NORMALIZATION."UNNEST_ALIAS__dbt_tmp" as DBT_INTERNAL_SOURCE
        on 
            DBT_INTERNAL_SOURCE._AIRBYTE_AB_ID = DBT_INTERNAL_DEST._AIRBYTE_AB_ID
        

    
    when matched then update set
        "ID" = DBT_INTERNAL_SOURCE."ID","CHILDREN" = DBT_INTERNAL_SOURCE."CHILDREN","_AIRBYTE_AB_ID" = DBT_INTERNAL_SOURCE."_AIRBYTE_AB_ID","_AIRBYTE_EMITTED_AT" = DBT_INTERNAL_SOURCE."_AIRBYTE_EMITTED_AT","_AIRBYTE_NORMALIZED_AT" = DBT_INTERNAL_SOURCE."_AIRBYTE_NORMALIZED_AT","_AIRBYTE_UNNEST_ALIAS_HASHID" = DBT_INTERNAL_SOURCE."_AIRBYTE_UNNEST_ALIAS_HASHID"
    

    when not matched then insert
        ("ID", "CHILDREN", "_AIRBYTE_AB_ID", "_AIRBYTE_EMITTED_AT", "_AIRBYTE_NORMALIZED_AT", "_AIRBYTE_UNNEST_ALIAS_HASHID")
    values
        ("ID", "CHILDREN", "_AIRBYTE_AB_ID", "_AIRBYTE_EMITTED_AT", "_AIRBYTE_NORMALIZED_AT", "_AIRBYTE_UNNEST_ALIAS_HASHID")

;
    commit;