/*
 * This file is generated by jOOQ.
 */
package io.airbyte.db.instance.jobs.jooq.enums;


import io.airbyte.db.instance.jobs.jooq.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum JobConfigType implements EnumType {

    check_connection_source("check_connection_source"),

    check_connection_destination("check_connection_destination"),

    discover_schema("discover_schema"),

    get_spec("get_spec"),

    sync("sync"),

    reset_connection("reset_connection");

    private final String literal;

    private JobConfigType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema() == null ? null : getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "job_config_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
