/*
 * This file is generated by jOOQ.
 */
package io.airbyte.db.instance.jobs.jooq.tables.records;


import io.airbyte.db.instance.jobs.jooq.tables.AirbyteMetadata;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AirbyteMetadataRecord extends UpdatableRecordImpl<AirbyteMetadataRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -295967569;

    /**
     * Setter for <code>public.airbyte_metadata.key</code>.
     */
    public void setKey(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.airbyte_metadata.key</code>.
     */
    public String getKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.airbyte_metadata.value</code>.
     */
    public void setValue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.airbyte_metadata.value</code>.
     */
    public String getValue() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return AirbyteMetadata.AIRBYTE_METADATA.KEY;
    }

    @Override
    public Field<String> field2() {
        return AirbyteMetadata.AIRBYTE_METADATA.VALUE;
    }

    @Override
    public String component1() {
        return getKey();
    }

    @Override
    public String component2() {
        return getValue();
    }

    @Override
    public String value1() {
        return getKey();
    }

    @Override
    public String value2() {
        return getValue();
    }

    @Override
    public AirbyteMetadataRecord value1(String value) {
        setKey(value);
        return this;
    }

    @Override
    public AirbyteMetadataRecord value2(String value) {
        setValue(value);
        return this;
    }

    @Override
    public AirbyteMetadataRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AirbyteMetadataRecord
     */
    public AirbyteMetadataRecord() {
        super(AirbyteMetadata.AIRBYTE_METADATA);
    }

    /**
     * Create a detached, initialised AirbyteMetadataRecord
     */
    public AirbyteMetadataRecord(String key, String value) {
        super(AirbyteMetadata.AIRBYTE_METADATA);

        set(0, key);
        set(1, value);
    }
}
