FROM airbyte/base-python-test:dev

RUN apt-get update && apt-get install -y \
    bash \
    && rm -rf /var/lib/apt/lists/*

ENV CODE_PATH="integration_tests"
ENV AIRBYTE_TEST_MODULE="integration_tests"
ENV AIRBYTE_TEST_PATH="RecurlyStandardSourceTest"
ENV AIRBYTE_TEST_CASE=true

LABEL io.airbyte.version=0.1.0
LABEL io.airbyte.name=airbyte/source-recurly-standard-test

WORKDIR /airbyte/integration_code
COPY $CODE_PATH ./$CODE_PATH

# copy all resources to the code path.
COPY secrets ./$CODE_PATH
COPY source_recurly/*.json ./$CODE_PATH

COPY setup.py ./
RUN pip install -v ".[integration_tests]"

WORKDIR /airbyte
