FROM airbyte/base-python-test:dev

RUN apt-get update && apt-get install -y bash && rm -rf /var/lib/apt/lists/*

ENV CODE_PATH="integration_tests"
ENV AIRBYTE_TEST_MODULE="integration_tests"
ENV AIRBYTE_TEST_PATH="RecurlyStandardSourceTest"

LABEL io.airbyte.version=0.1.0
LABEL io.airbyte.name=airbyte/source-recurly-standard-test


WORKDIR /airbyte/integration_code
COPY source_recurly source_recurly
COPY $CODE_PATH $CODE_PATH
COPY secrets/* $CODE_PATH
COPY source_recurly/*.json $CODE_PATH
COPY setup.py ./

RUN pip install ".[tests]"

WORKDIR /airbyte
