FROM airbyte/base-python-test:dev

RUN apt-get update && apt-get install -y \
    bash \
    && rm -rf /var/lib/apt/lists/*

ENV CODE_PATH="integration_tests"
ENV AIRBYTE_IMPL_MODULE="integration_tests"
ENV AIRBYTE_IMPL_PATH="GoogleSheetsSourceStandardTest"
ENV AIRBYTE_TEST_CASE=true

LABEL io.airbyte.version=0.1.0
LABEL io.airbyte.name=airbyte/source-google-sheets-standard-test

WORKDIR /airbyte/integration_code
COPY . .
COPY secrets/* ./integration_tests/
RUN pip install ".[standardtest]"

WORKDIR /airbyte
