FROM airbyte/base-python-test:dev

RUN apt-get update && apt-get install -y \
    && rm -rf /var/lib/apt/lists/*

ENV CODE_PATH="integration_tests"
ENV AIRBYTE_TEST_MODULE="integration_tests"
ENV AIRBYTE_TEST_PATH="GoogleSheetsSourceStandardTest"
ENV AIRBYTE_TEST_CASE=true

LABEL io.airbyte.version=0.1.0
LABEL io.airbyte.name=airbyte/source-google-sheets-standard-test

WORKDIR /airbyte/integration_code
COPY google_sheets_source google_sheets_source
COPY integration_tests integration_tests
COPY secrets/* integration_tests
COPY google_sheets_source/*.json integration_tests
COPY setup.py ./

RUN pip install ".[integration_tests]"

WORKDIR /airbyte
