[build-system]
requires = ["poetry-core>=1.0.0,<2.0.0"]
build-backend = "poetry.core.masonry.api"
[tool.poetry]
name = "source-github-tests"
version = "0.1.0"
description = "Unit tests for source-github"
authors = [
    "Airbyte <contact@airbyte.io>"
]
package-mode = false
[tool.poetry.dependencies]
python = "^3.10,<3.14"
pytest = "^8"
airbyte-cdk = "^7.30.0"
requests-mock = "^1.12"
pytest-mock = "^3"
freezegun = "^1.2"
responses = "^0.23.1"
[tool.pytest.ini_options]
filterwarnings = [
    "ignore:This class is experimental*"
]
