/*
 * Copyright (c) 2026 Airbyte, Inc., all rights reserved.
 */

package io.airbyte.integrations.source.mysql

import java.math.BigInteger

/** First code point of the UTF-16 surrogate range (inclusive). */
private const val SURROGATE_LOW = 0xD800

/** Last code point of the UTF-16 surrogate range (inclusive). */
private const val SURROGATE_HIGH = 0xDFFF

/** Number of code points reserved for surrogates, which are not valid Unicode scalar values. */
private const val SURROGATE_COUNT = SURROGATE_HIGH - SURROGATE_LOW + 1

/**
 * Maps a Unicode scalar code point to a contiguous, surrogate-free index. Code points at or above
 * the surrogate block are shifted down so that the resulting index space contains no gaps, which
 * keeps positional-numeral arithmetic order-preserving and prevents surrogate code points from
 * being emitted.
 */
private fun codePointToIndex(cp: Int): Int = if (cp < SURROGATE_LOW) cp else cp - SURROGATE_COUNT

/** Inverse of [codePointToIndex]. */
private fun indexToCodePoint(index: Int): Int =
    if (index < SURROGATE_LOW) index else index + SURROGATE_COUNT

/**
 * Converts a list of integers to a BigInteger using the specified base. This treats the list as
 * digits in a positional numeral system.
 */
private fun intListToBigInt(values: List<Int>, base: BigInteger): BigInteger {
    var result = BigInteger.ZERO
    for (value in values) {
        result = result.multiply(base).add(BigInteger.valueOf(value.toLong()))
    }
    return result
}

/**
 * Converts a BigInteger back to a list of integers of the specified length using the specified
 * base. This is the inverse operation of intListToBigInt.
 */
private fun bigIntToIntList(num: BigInteger, length: Int, base: BigInteger): List<Int> {
    var n = num
    val result = MutableList(length) { 0 }
    for (i in (length - 1) downTo 0) {
        val rem = n.mod(base).toInt()
        result[i] = rem
        n = n.divide(base)
    }
    return result
}

/**
 * Generates interpolated strings between start and end using Unicode code points. The strings are
 * generated by treating them as digits in a positional numeral system.
 *
 * The numeral base is derived from the largest code point present in [start] and [end] rather than
 * the full Unicode range. Because the interpolation endpoints are the actual primary-key bounds
 * read from (and compared against) the source column, every code point they contain is by
 * definition representable in that column's character set. Restricting synthetic boundaries to that
 * same range therefore keeps them collation-compatible: interpolating between ASCII (e.g. GUID)
 * bounds yields ASCII-only values, avoiding supplementary-plane (`utf8mb4`-only) characters that
 * MySQL/MariaDB reject with error 1267 when compared against a narrower-charset (`utf8`/`utf8mb3`)
 * column. Surrogate code points are skipped so only valid Unicode scalar values are produced.
 */
fun unicodeInterpolatedStrings(start: String, end: String, steps: Int): List<String> {
    fun toIndices(s: String): List<Int> {
        val indices = mutableListOf<Int>()
        var i = 0
        while (i < s.length) {
            val cp = s.codePointAt(i)
            indices.add(codePointToIndex(cp))
            i += Character.charCount(cp)
        }
        return indices
    }

    fun fromIndices(indices: List<Int>): String {
        val sb = StringBuilder()
        for (idx in indices) {
            sb.append(Character.toChars(indexToCodePoint(idx)))
        }
        return sb.toString()
    }

    val a = toIndices(start)
    val b = toIndices(end)
    // Base = largest code-point index in either bound + 1, so no synthetic value ever exceeds the
    // widest character already stored in the column. A minimum of 1 keeps the arithmetic valid when
    // both bounds are empty.
    val maxIndex = maxOf(a.maxOrNull() ?: 0, b.maxOrNull() ?: 0)
    val base = BigInteger.valueOf((maxIndex + 1).toLong())
    val maxLen = maxOf(a.size, b.size)
    val aPadded = a + List(maxLen - a.size) { 0 }
    val bPadded = b + List(maxLen - b.size) { 0 }

    val aNum = intListToBigInt(aPadded, base)
    val bNum = intListToBigInt(bPadded, base)

    val result = mutableListOf<String>()
    for (i in 0..steps) {
        val mid =
            if (steps == 0) {
                aNum
            } else {
                val fraction =
                    BigInteger.valueOf(i.toLong())
                        .multiply(bNum - aNum)
                        .divide(BigInteger.valueOf(steps.toLong()))
                aNum + fraction
            }
        val indices = bigIntToIntList(mid, maxLen, base)
        result.add(
            when (i) {
                0 -> start
                steps -> end
                else -> fromIndices(indices)
            }
        )
    }

    return result
}

/**
 * Generates interpolated strings between start and end using GUID-legal characters. This is
 * optimized for GUID/UUID strings which only use hexadecimal and hyphen characters.
 */
fun guidInterpolatedStrings(start: String, end: String, steps: Int): List<String> {
    // GUID-legal characters: 0-9, A-F, a-f, and hyphen (case-sensitive, ASCII order)
    val guidChars = "-0123456789ABCDEFabcdef"

    fun charToIndex(c: Char): Int {
        val idx = guidChars.indexOf(c)
        if (idx == -1) {
            throw IllegalArgumentException("Character '$c' is not GUID-legal")
        }
        return idx
    }

    fun indexToChar(idx: Int): Char {
        if (idx < 0 || idx >= guidChars.length) {
            throw IllegalArgumentException("Index $idx out of range for GUID characters")
        }
        return guidChars[idx]
    }

    fun toIndices(s: String): List<Int> {
        return s.map { charToIndex(it) }
    }

    fun fromIndices(indices: List<Int>): String {
        return indices.map { indexToChar(it) }.joinToString("")
    }

    val base =
        BigInteger.valueOf(guidChars.length.toLong()) // 23 valid GUID characters (case-sensitive)
    val a = toIndices(start)
    val b = toIndices(end)
    val maxLen = maxOf(a.size, b.size)
    val aPadded = a + List(maxLen - a.size) { 0 }
    val bPadded = b + List(maxLen - b.size) { 0 }

    val aNum = intListToBigInt(aPadded, base)
    val bNum = intListToBigInt(bPadded, base)

    val result = mutableListOf<String>()
    for (i in 0..steps) {
        val mid =
            if (steps == 0) {
                aNum
            } else {
                val fraction =
                    BigInteger.valueOf(i.toLong())
                        .multiply(bNum - aNum)
                        .divide(BigInteger.valueOf(steps.toLong()))
                aNum + fraction
            }
        val indices = bigIntToIntList(mid, maxLen, base)
        result.add(fromIndices(indices))
    }

    return result
}
