FROM airbyte/base-python-test:dev

RUN apt-get update && apt-get install -y \
    bash \
    && rm -rf /var/lib/apt/lists/*

ENV CODE_PATH="standardtest"
ENV AIRBYTE_IMPL_MODULE="standardtest"
ENV AIRBYTE_IMPL_PATH="GithubStandardSourceTest"
ENV AIRBYTE_TEST_CASE=true

LABEL io.airbyte.version=0.1.0
LABEL io.airbyte.name=airbyte/source-github-singer-standard-test

WORKDIR /airbyte/integration_code

# copy all resources to the code path.
COPY secrets ./$CODE_PATH
COPY source_github_singer/*.json ./$CODE_PATH
COPY resourcesstandardtest/*.json ./$CODE_PATH

COPY setup.py ./
RUN pip install ".[standardtest]"

WORKDIR /airbyte

