/*
 * This file is generated by jOOQ.
 */
package io.airbyte.db.instance.jobs.jooq.routines;


import io.airbyte.db.instance.jobs.jooq.Public;

import java.util.UUID;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UuidNsOid extends AbstractRoutine<UUID> {

    private static final long serialVersionUID = 439978576;

    /**
     * The parameter <code>public.uuid_ns_oid.RETURN_VALUE</code>.
     */
    public static final Parameter<UUID> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.UUID, false, false);

    /**
     * Create a new routine call instance
     */
    public UuidNsOid() {
        super("uuid_ns_oid", Public.PUBLIC, org.jooq.impl.SQLDataType.UUID);

        setReturnParameter(RETURN_VALUE);
    }
}
