# See [Connector Acceptance Tests](https://docs.airbyte.com/connector-development/testing-connectors/connector-acceptance-tests-reference)
# for more information about how to configure these tests
connector_image: airbyte/source-quickbooks:dev
test_strictness_level: "low"
acceptance_tests:
  spec:
    tests:
      - spec_path: "manifest.yaml"
        backward_compatibility_tests_config:
          disable_for_version: "1.0.0"
  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
      - config_path: "integration_tests/invalid_config.json"
        status: "failed"
  discovery:
    tests:
      - config_path: "secrets/config.json"
        backward_compatibility_tests_config:
          disable_for_version: "2.0.0" #change type of a field in payments schema
  basic_read:
    tests:
      - config_path: "secrets/config.json"
        empty_streams:
          - name: attachables
            bypass_reason: "The sandbox company has no Attachable records"
          - name: bill_payments
            bypass_reason: "The sandbox company has no BillPayment records"
          - name: bills
            bypass_reason: "The sandbox company has no Bill records"
          - name: budgets
            bypass_reason: "The sandbox company has no Budget records"
          - name: classes
            bypass_reason: "The sandbox company has no Class records"
          - name: credit_card_payments
            bypass_reason: "The sandbox company has no CreditCardPaymentTxn records"
          - name: credit_memos
            bypass_reason: "The sandbox company has no CreditMemo records"
          - name: departments
            bypass_reason: "The sandbox company has no Department records"
          - name: employees
            bypass_reason: "The sandbox company has no Employee records"
          - name: items
            bypass_reason: "The sandbox company has no Item records"
          - name: journal_entries
            bypass_reason: "The sandbox company has no JournalEntry records"
          - name: payment_methods
            bypass_reason: "The sandbox company has no PaymentMethod records"
          - name: payments
            bypass_reason: "The sandbox company has no Payment records"
          - name: purchase_orders
            bypass_reason: "The sandbox company has no PurchaseOrder records"
          - name: purchases
            bypass_reason: "The sandbox company has no Purchase records"
          - name: refund_receipts
            bypass_reason: "The sandbox company has no RefundReceipt records"
          - name: sales_receipts
            bypass_reason: "The sandbox company has no SalesReceipt records"
          - name: tax_agencies
            bypass_reason: "The sandbox company has no TaxAgency records"
          - name: tax_codes
            bypass_reason: "The sandbox company has no TaxCode records"
          - name: tax_rates
            bypass_reason: "The sandbox company has no TaxRate records"
          - name: terms
            bypass_reason: "The sandbox company has no Term records"
          - name: time_activities
            bypass_reason: "The sandbox company has no TimeActivity records"
          - name: transfers
            bypass_reason: "The sandbox company has no Transfer records"
          - name: vendor_credits
            bypass_reason: "The sandbox company has no VendorCredit records"
          - name: vendors
            bypass_reason: "The sandbox company has no Vendor records"
  incremental:
    tests:
      - config_path: "secrets/config.json"
        future_state:
          future_state_path: "integration_tests/abnormal_state.json"
  full_refresh:
    tests:
      - config_path: "secrets/config.json"
