/*
 * Copyright (c) 2021 Airbyte, Inc., all rights reserved.
 */

package io.airbyte.config.persistence;

import io.airbyte.commons.json.Jsons;
import io.airbyte.config.persistence.split_secrets.JsonSecretsProcessor;
import org.junit.jupiter.api.Test;

public class TestToShowJsonException {

  @Test
  public void tesmte() {
    JsonSecretsProcessor build = JsonSecretsProcessor.builder()
        .maskSecrets(true)
        .copySecrets(true)
        .build();

    build.prepareSecretsForOutput(Jsons.deserialize(jsonObject), Jsons.deserialize(jsonSchema));
  }

  String jsonObject = "{\n"
      + "    \"account_id\": \"1234567891234567\",\n"
      + "    \"start_date\": \"2022-04-01T00:00:00Z\",\n"
      + "    \"access_token\": {\n"
      + "        \"_secret\": \"airbyte_workspace_12345678-1234-1234-ab12-a1b234567c1a_secret_1aab1234-123a-1234-a123-1234abcde123_v1\"\n"
      + "    },\n"
      + "    \"include_deleted\": false,\n"
      + "    \"fetch_thumbnail_images\": false\n"
      + "}";


  String jsonSchema = "{\n"
      + "        \"type\": \"object\",\n"
      + "        \"title\": \"Source Facebook Marketing\",\n"
      + "        \"required\": [\n"
      + "            \"account_id\",\n"
      + "            \"start_date\",\n"
      + "            \"access_token\"\n"
      + "        ],\n"
      + "        \"properties\": {\n"
      + "            \"end_date\": {\n"
      + "                \"type\": \"string\",\n"
      + "                \"order\": 2,\n"
      + "                \"title\": \"End Date\",\n"
      + "                \"format\": \"date-time\",\n"
      + "                \"pattern\": \"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$\",\n"
      + "                \"examples\": [\n"
      + "                    \"2017-01-26T00:00:00Z\"\n"
      + "                ],\n"
      + "                \"description\": \"The date until which you'd like to replicate data for all incremental streams, in the format YYYY-MM-DDT00:00:00Z. All data generated between start_date and this date will be replicated. Not setting this option will result in always syncing the latest data.\"\n"
      + "            },\n"
      + "            \"account_id\": {\n"
      + "                \"type\": \"string\",\n"
      + "                \"order\": 0,\n"
      + "                \"title\": \"Account ID\",\n"
      + "                \"examples\": [\n"
      + "                    \"111111111111111\"\n"
      + "                ],\n"
      + "                \"description\": \"The Facebook Ad account ID to use when pulling data from the Facebook Marketing API.\"\n"
      + "            },\n"
      + "            \"start_date\": {\n"
      + "                \"type\": \"string\",\n"
      + "                \"order\": 1,\n"
      + "                \"title\": \"Start Date\",\n"
      + "                \"format\": \"date-time\",\n"
      + "                \"pattern\": \"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$\",\n"
      + "                \"examples\": [\n"
      + "                    \"2017-01-25T00:00:00Z\"\n"
      + "                ],\n"
      + "                \"description\": \"The date from which you'd like to replicate data for all incremental streams, in the format YYYY-MM-DDT00:00:00Z. All data generated after this date will be replicated.\"\n"
      + "            },\n"
      + "            \"access_token\": {\n"
      + "                \"type\": \"string\",\n"
      + "                \"order\": 3,\n"
      + "                \"title\": \"Access Token\",\n"
      + "                \"description\": \"The value of the access token generated. See the <a href=\\\"https://docs.airbyte.io/integrations/sources/facebook-marketing\\\">docs</a> for more information\",\n"
      + "                \"airbyte_secret\": true\n"
      + "            },\n"
      + "            \"custom_insights\": {\n"
      + "                \"type\": \"array\",\n"
      + "                \"items\": {\n"
      + "                    \"type\": \"object\",\n"
      + "                    \"title\": \"InsightConfig\",\n"
      + "                    \"required\": [\n"
      + "                        \"name\"\n"
      + "                    ],\n"
      + "                    \"properties\": {\n"
      + "                        \"name\": {\n"
      + "                            \"type\": \"string\",\n"
      + "                            \"title\": \"Name\",\n"
      + "                            \"description\": \"The name value of insight\"\n"
      + "                        },\n"
      + "                        \"fields\": {\n"
      + "                            \"type\": \"array\",\n"
      + "                            \"items\": {\n"
      + "                                \"enum\": [\n"
      + "                                    \"account_currency\",\n"
      + "                                    \"account_id\",\n"
      + "                                    \"account_name\",\n"
      + "                                    \"action_values\",\n"
      + "                                    \"actions\",\n"
      + "                                    \"ad_bid_value\",\n"
      + "                                    \"ad_click_actions\",\n"
      + "                                    \"ad_id\",\n"
      + "                                    \"ad_impression_actions\",\n"
      + "                                    \"ad_name\",\n"
      + "                                    \"adset_bid_value\",\n"
      + "                                    \"adset_end\",\n"
      + "                                    \"adset_id\",\n"
      + "                                    \"adset_name\",\n"
      + "                                    \"adset_start\",\n"
      + "                                    \"age_targeting\",\n"
      + "                                    \"attribution_setting\",\n"
      + "                                    \"auction_bid\",\n"
      + "                                    \"auction_competitiveness\",\n"
      + "                                    \"auction_max_competitor_bid\",\n"
      + "                                    \"buying_type\",\n"
      + "                                    \"campaign_id\",\n"
      + "                                    \"campaign_name\",\n"
      + "                                    \"canvas_avg_view_percent\",\n"
      + "                                    \"canvas_avg_view_time\",\n"
      + "                                    \"catalog_segment_actions\",\n"
      + "                                    \"catalog_segment_value\",\n"
      + "                                    \"catalog_segment_value_mobile_purchase_roas\",\n"
      + "                                    \"catalog_segment_value_omni_purchase_roas\",\n"
      + "                                    \"catalog_segment_value_website_purchase_roas\",\n"
      + "                                    \"clicks\",\n"
      + "                                    \"conversion_rate_ranking\",\n"
      + "                                    \"conversion_values\",\n"
      + "                                    \"conversions\",\n"
      + "                                    \"converted_product_quantity\",\n"
      + "                                    \"converted_product_value\",\n"
      + "                                    \"cost_per_15_sec_video_view\",\n"
      + "                                    \"cost_per_2_sec_continuous_video_view\",\n"
      + "                                    \"cost_per_action_type\",\n"
      + "                                    \"cost_per_ad_click\",\n"
      + "                                    \"cost_per_conversion\",\n"
      + "                                    \"cost_per_dda_countby_convs\",\n"
      + "                                    \"cost_per_estimated_ad_recallers\",\n"
      + "                                    \"cost_per_inline_link_click\",\n"
      + "                                    \"cost_per_inline_post_engagement\",\n"
      + "                                    \"cost_per_one_thousand_ad_impression\",\n"
      + "                                    \"cost_per_outbound_click\",\n"
      + "                                    \"cost_per_thruplay\",\n"
      + "                                    \"cost_per_unique_action_type\",\n"
      + "                                    \"cost_per_unique_click\",\n"
      + "                                    \"cost_per_unique_conversion\",\n"
      + "                                    \"cost_per_unique_inline_link_click\",\n"
      + "                                    \"cost_per_unique_outbound_click\",\n"
      + "                                    \"cpc\",\n"
      + "                                    \"cpm\",\n"
      + "                                    \"cpp\",\n"
      + "                                    \"created_time\",\n"
      + "                                    \"ctr\",\n"
      + "                                    \"date_start\",\n"
      + "                                    \"date_stop\",\n"
      + "                                    \"dda_countby_convs\",\n"
      + "                                    \"dda_results\",\n"
      + "                                    \"engagement_rate_ranking\",\n"
      + "                                    \"estimated_ad_recall_rate\",\n"
      + "                                    \"estimated_ad_recall_rate_lower_bound\",\n"
      + "                                    \"estimated_ad_recall_rate_upper_bound\",\n"
      + "                                    \"estimated_ad_recallers\",\n"
      + "                                    \"estimated_ad_recallers_lower_bound\",\n"
      + "                                    \"estimated_ad_recallers_upper_bound\",\n"
      + "                                    \"frequency\",\n"
      + "                                    \"full_view_impressions\",\n"
      + "                                    \"full_view_reach\",\n"
      + "                                    \"gender_targeting\",\n"
      + "                                    \"impressions\",\n"
      + "                                    \"inline_link_click_ctr\",\n"
      + "                                    \"inline_link_clicks\",\n"
      + "                                    \"inline_post_engagement\",\n"
      + "                                    \"instant_experience_clicks_to_open\",\n"
      + "                                    \"instant_experience_clicks_to_start\",\n"
      + "                                    \"instant_experience_outbound_clicks\",\n"
      + "                                    \"interactive_component_tap\",\n"
      + "                                    \"labels\",\n"
      + "                                    \"location\",\n"
      + "                                    \"mobile_app_purchase_roas\",\n"
      + "                                    \"objective\",\n"
      + "                                    \"optimization_goal\",\n"
      + "                                    \"outbound_clicks\",\n"
      + "                                    \"outbound_clicks_ctr\",\n"
      + "                                    \"place_page_name\",\n"
      + "                                    \"purchase_roas\",\n"
      + "                                    \"qualifying_question_qualify_answer_rate\",\n"
      + "                                    \"quality_ranking\",\n"
      + "                                    \"quality_score_ectr\",\n"
      + "                                    \"quality_score_ecvr\",\n"
      + "                                    \"quality_score_organic\",\n"
      + "                                    \"reach\",\n"
      + "                                    \"social_spend\",\n"
      + "                                    \"spend\",\n"
      + "                                    \"total_postbacks\",\n"
      + "                                    \"unique_actions\",\n"
      + "                                    \"unique_clicks\",\n"
      + "                                    \"unique_conversions\",\n"
      + "                                    \"unique_ctr\",\n"
      + "                                    \"unique_inline_link_click_ctr\",\n"
      + "                                    \"unique_inline_link_clicks\",\n"
      + "                                    \"unique_link_clicks_ctr\",\n"
      + "                                    \"unique_outbound_clicks\",\n"
      + "                                    \"unique_outbound_clicks_ctr\",\n"
      + "                                    \"unique_video_continuous_2_sec_watched_actions\",\n"
      + "                                    \"unique_video_view_15_sec\",\n"
      + "                                    \"updated_time\",\n"
      + "                                    \"video_15_sec_watched_actions\",\n"
      + "                                    \"video_30_sec_watched_actions\",\n"
      + "                                    \"video_avg_time_watched_actions\",\n"
      + "                                    \"video_continuous_2_sec_watched_actions\",\n"
      + "                                    \"video_p100_watched_actions\",\n"
      + "                                    \"video_p25_watched_actions\",\n"
      + "                                    \"video_p50_watched_actions\",\n"
      + "                                    \"video_p75_watched_actions\",\n"
      + "                                    \"video_p95_watched_actions\",\n"
      + "                                    \"video_play_actions\",\n"
      + "                                    \"video_play_curve_actions\",\n"
      + "                                    \"video_play_retention_0_to_15s_actions\",\n"
      + "                                    \"video_play_retention_20_to_60s_actions\",\n"
      + "                                    \"video_play_retention_graph_actions\",\n"
      + "                                    \"video_thruplay_watched_actions\",\n"
      + "                                    \"video_time_watched_actions\",\n"
      + "                                    \"website_ctr\",\n"
      + "                                    \"website_purchase_roas\",\n"
      + "                                    \"wish_bid\"\n"
      + "                                ],\n"
      + "                                \"title\": \"ValidEnums\",\n"
      + "                                \"description\": \"Generic enumeration.\\n\\nDerive from this class to define new enumerations.\"\n"
      + "                            },\n"
      + "                            \"title\": \"Fields\",\n"
      + "                            \"default\": [],\n"
      + "                            \"description\": \"A list of chosen fields for fields parameter\"\n"
      + "                        },\n"
      + "                        \"end_date\": {\n"
      + "                            \"type\": \"string\",\n"
      + "                            \"title\": \"End Date\",\n"
      + "                            \"format\": \"date-time\",\n"
      + "                            \"pattern\": \"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$\",\n"
      + "                            \"examples\": [\n"
      + "                                \"2017-01-26T00:00:00Z\"\n"
      + "                            ],\n"
      + "                            \"description\": \"The date until which you'd like to replicate data for this stream, in the format YYYY-MM-DDT00:00:00Z. All data generated between the start date and this date will be replicated. Not setting this option will result in always syncing the latest data.\"\n"
      + "                        },\n"
      + "                        \"breakdowns\": {\n"
      + "                            \"type\": \"array\",\n"
      + "                            \"items\": {\n"
      + "                                \"enum\": [\n"
      + "                                    \"ad_format_asset\",\n"
      + "                                    \"age\",\n"
      + "                                    \"app_id\",\n"
      + "                                    \"body_asset\",\n"
      + "                                    \"call_to_action_asset\",\n"
      + "                                    \"country\",\n"
      + "                                    \"description_asset\",\n"
      + "                                    \"device_platform\",\n"
      + "                                    \"dma\",\n"
      + "                                    \"frequency_value\",\n"
      + "                                    \"gender\",\n"
      + "                                    \"hourly_stats_aggregated_by_advertiser_time_zone\",\n"
      + "                                    \"hourly_stats_aggregated_by_audience_time_zone\",\n"
      + "                                    \"image_asset\",\n"
      + "                                    \"impression_device\",\n"
      + "                                    \"link_url_asset\",\n"
      + "                                    \"place_page_id\",\n"
      + "                                    \"platform_position\",\n"
      + "                                    \"product_id\",\n"
      + "                                    \"publisher_platform\",\n"
      + "                                    \"region\",\n"
      + "                                    \"skan_conversion_id\",\n"
      + "                                    \"title_asset\",\n"
      + "                                    \"video_asset\"\n"
      + "                                ],\n"
      + "                                \"title\": \"ValidBreakdowns\",\n"
      + "                                \"description\": \"Generic enumeration.\\n\\nDerive from this class to define new enumerations.\"\n"
      + "                            },\n"
      + "                            \"title\": \"Breakdowns\",\n"
      + "                            \"default\": [],\n"
      + "                            \"description\": \"A list of chosen breakdowns for breakdowns\"\n"
      + "                        },\n"
      + "                        \"start_date\": {\n"
      + "                            \"type\": \"string\",\n"
      + "                            \"title\": \"Start Date\",\n"
      + "                            \"format\": \"date-time\",\n"
      + "                            \"pattern\": \"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$\",\n"
      + "                            \"examples\": [\n"
      + "                                \"2017-01-25T00:00:00Z\"\n"
      + "                            ],\n"
      + "                            \"description\": \"The date from which you'd like to replicate data for this stream, in the format YYYY-MM-DDT00:00:00Z.\"\n"
      + "                        },\n"
      + "                        \"time_increment\": {\n"
      + "                            \"type\": \"integer\",\n"
      + "                            \"title\": \"Time Increment\",\n"
      + "                            \"default\": 1,\n"
      + "                            \"description\": \"Time window in days by which to aggregate statistics. The sync will be chunked into N day intervals, where N is the number of days you specified. For example, if you set this value to 7, then all statistics will be reported as 7-day aggregates by starting from the start_date. If the start and end dates are October 1st and October 30th, then the connector will output 5 records: 01 - 06, 07 - 13, 14 - 20, 21 - 27, and 28 - 30 (3 days only).\",\n"
      + "                            \"exclusiveMaximum\": 90,\n"
      + "                            \"exclusiveMinimum\": 0\n"
      + "                        },\n"
      + "                        \"action_breakdowns\": {\n"
      + "                            \"type\": \"array\",\n"
      + "                            \"items\": {\n"
      + "                                \"enum\": [\n"
      + "                                    \"action_canvas_component_name\",\n"
      + "                                    \"action_carousel_card_id\",\n"
      + "                                    \"action_carousel_card_name\",\n"
      + "                                    \"action_destination\",\n"
      + "                                    \"action_device\",\n"
      + "                                    \"action_reaction\",\n"
      + "                                    \"action_target_id\",\n"
      + "                                    \"action_type\",\n"
      + "                                    \"action_video_sound\",\n"
      + "                                    \"action_video_type\"\n"
      + "                                ],\n"
      + "                                \"title\": \"ValidActionBreakdowns\",\n"
      + "                                \"description\": \"Generic enumeration.\\n\\nDerive from this class to define new enumerations.\"\n"
      + "                            },\n"
      + "                            \"title\": \"Action Breakdowns\",\n"
      + "                            \"default\": [],\n"
      + "                            \"description\": \"A list of chosen action_breakdowns for action_breakdowns\"\n"
      + "                        }\n"
      + "                    },\n"
      + "                    \"description\": \"Config for custom insights\"\n"
      + "                },\n"
      + "                \"order\": 6,\n"
      + "                \"title\": \"Custom Insights\",\n"
      + "                \"description\": \"A list which contains insights entries, each entry must have a name and can contains fields, breakdowns or action_breakdowns)\"\n"
      + "            },\n"
      + "            \"include_deleted\": {\n"
      + "                \"type\": \"boolean\",\n"
      + "                \"order\": 4,\n"
      + "                \"title\": \"Include Deleted\",\n"
      + "                \"default\": false,\n"
      + "                \"description\": \"Include data from deleted Campaigns, Ads, and AdSets\"\n"
      + "            },\n"
      + "            \"fetch_thumbnail_images\": {\n"
      + "                \"type\": \"boolean\",\n"
      + "                \"order\": 5,\n"
      + "                \"title\": \"Fetch Thumbnail Images\",\n"
      + "                \"default\": false,\n"
      + "                \"description\": \"In each Ad Creative, fetch the thumbnail_url and store the result in thumbnail_data_url\"\n"
      + "            }\n"
      + "        }\n"
      + "    }";

}
