FROM airbyte/base-python-test:dev

# Bash is installed for convenient debugging.
RUN apt-get update && apt-get install -y bash && rm -rf /var/lib/apt/lists/*

ENV MODULE_NAME="source_marketo_singer"
ENV CODE_PATH="integration_tests"
ENV AIRBYTE_TEST_MODULE="integration_tests"
ENV AIRBYTE_TEST_PATH="SourceMarketoSingerStandardTest"

LABEL io.airbyte.version=0.1.0
LABEL io.airbyte.name=airbyte/source-marketo-singer-standard-test

WORKDIR /airbyte/integration_code
COPY $MODULE_NAME $MODULE_NAME
COPY $CODE_PATH $CODE_PATH
COPY secrets/* $CODE_PATH/
COPY $MODULE_NAME/*.json $CODE_PATH
COPY setup.py ./

RUN pip install ".[tests]"

WORKDIR /airbyte
