
  create or replace  view "INTEGRATION_TEST_NORMALIZATION"._AIRBYTE_TEST_NORMALIZATION."DEDUP_EXCHANGE_RATE_SCD_NEW_DATA" 
  
   as (
    
-- depends_on: ref('DEDUP_EXCHANGE_RATE_STG')

select * from "INTEGRATION_TEST_NORMALIZATION"._AIRBYTE_TEST_NORMALIZATION."DEDUP_EXCHANGE_RATE_STG"


  );
