FROM airbyte/base-python-test:dev

RUN apt-get update && apt-get install -y bash && rm -rf /var/lib/apt/lists/*

ENV CODE_PATH="integration_tests"
ENV AIRBYTE_TEST_MODULE="integration_tests"
ENV AIRBYTE_TEST_PATH="SourceLookerStandardTest"

LABEL io.airbyte.version=0.1.0
LABEL io.airbyte.name=airbyte/source-looker-standard-test

WORKDIR /airbyte/integration_code
COPY source_looker source_looker
COPY $CODE_PATH $CODE_PATH
COPY secrets/* $CODE_PATH/
COPY source_looker/*.json $CODE_PATH/
COPY setup.py ./

RUN pip install ".[tests]"

WORKDIR /airbyte
