ADS_DEFAULT_FIELDS = {
    "FieldNames": [
        "AdCategories",
        "AgeLabel",
        "AdGroupId",
        "CampaignId",
        "Id",
        "State",
        "Status",
        "StatusClarification",
        "Type",
        "Subtype",
    ],
    "TextAdFieldNames": [
        "AdImageHash",
        "DisplayDomain",
        "Href",
        "SitelinkSetId",
        "Text",
        "Title",
        "Title2",
        "Mobile",
        "VCardId",
        "DisplayUrlPath",
        "AdImageModeration",
        "SitelinksModeration",
        "VCardModeration",
        "AdExtensions",
        "DisplayUrlPathModeration",
        "VideoExtension",
        "TurboPageId",
        "TurboPageModeration",
        "BusinessId",
    ],
    "TextAdPriceExtensionFieldNames": ["Price", "OldPrice", "PriceCurrency", "PriceQualifier"],
    "MobileAppAdFieldNames": [
        "AdImageHash",
        "AdImageModeration",
        "Title",
        "Text",
        "Features",
        "Action",
        "TrackingUrl",
        "VideoExtension",
    ],
    "DynamicTextAdFieldNames": [
        "AdImageHash",
        "SitelinkSetId",
        "Text",
        "VCardId",
        "AdImageModeration",
        "SitelinksModeration",
        "VCardModeration",
        "AdExtensions",
    ],
    "TextImageAdFieldNames": ["AdImageHash", "Href", "TurboPageId", "TurboPageModeration"],
    "MobileAppImageAdFieldNames": ["AdImageHash", "TrackingUrl"],
    "TextAdBuilderAdFieldNames": ["Creative", "Href", "TurboPageId", "TurboPageModeration"],
    "MobileAppAdBuilderAdFieldNames": ["Creative", "TrackingUrl"],
    "MobileAppCpcVideoAdBuilderAdFieldNames": ["Creative", "TrackingUrl"],
    "CpcVideoAdBuilderAdFieldNames": ["Creative", "Href", "TurboPageId", "TurboPageModeration"],
    "CpmBannerAdBuilderAdFieldNames": ["Creative", "Href", "TrackingPixels", "TurboPageId", "TurboPageModeration"],
    "CpmVideoAdBuilderAdFieldNames": ["Creative", "Href", "TrackingPixels", "TurboPageId", "TurboPageModeration"],
    "SmartAdBuilderAdFieldNames": ["Creative"],
}

AD_IMAGES_DEFAULT_FIELDS = {
    "FieldNames": ["AdImageHash", "OriginalUrl", "PreviewUrl", "Name", "Type", "Subtype", "Associated"],
}

CAMPAIGNS_DEFAULT_FIELDS = {
    "FieldNames": [
        "Id",
        "Name",
        "StartDate",
        "Type",
        "Status",
        "State",
        "StatusPayment",
        "StatusClarification",
        "SourceId",
        "Currency",
    ],
}
