FROM airbyte/base-python-test:dev

RUN apt-get update && rm -rf /var/lib/apt/lists/*

ENV CODE_PATH="integration_tests"
ENV AIRBYTE_TEST_MODULE="integration_tests"
ENV AIRBYTE_TEST_PATH="SourceGoogleAdwordsSingerStandardTest"
ENV AIRBYTE_TEST_CASE=true

LABEL io.airbyte.version=0.1.0
LABEL io.airbyte.name=airbyte/source-google-adwords-singer-standard-test

WORKDIR /airbyte/integration_code
COPY $CODE_PATH $CODE_PATH/
COPY secrets/* $CODE_PATH/
COPY sample_files/* $CODE_PATH/
COPY source_google_adwords_singer/*.json $CODE_PATH/
COPY setup.py ./

RUN pip install ".[tests]"

WORKDIR /airbyte
