package io.dataline.config.persistence;

public enum PersistenceConfigType {
  SOURCE_CONNECTION_IMPLEMENTATION,
  STANDARD_CONNECTION_STATUS,
  STANDARD_DISCOVERY_OUTPUT,
  DESTINATION_CONNECTION_CONFIGURATION,
  STANDARD_SYNC_CONFIGURATION,
  STANDARD_SYNC_SUMMARY,
  STANDARD_SYNC_STATE,
  STATE,
  STANDARD_SYNC_SCHEDULE,
  STANDARD_WORKSPACE_CONFIGURATION,
  STANDARD_SOURCE,
  SOURCE_CONNECTION_SPECIFICATION
}
