/*
 * This file is generated by jOOQ.
 */
package io.airbyte.db.instance.jobs.jooq;


import io.airbyte.db.instance.jobs.jooq.tables.AirbyteMetadata;
import io.airbyte.db.instance.jobs.jooq.tables.Attempts;
import io.airbyte.db.instance.jobs.jooq.tables.Jobs;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 52897270;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.airbyte_metadata</code>.
     */
    public final AirbyteMetadata AIRBYTE_METADATA = AirbyteMetadata.AIRBYTE_METADATA;

    /**
     * The table <code>public.attempts</code>.
     */
    public final Attempts ATTEMPTS = Attempts.ATTEMPTS;

    /**
     * The table <code>public.jobs</code>.
     */
    public final Jobs JOBS = Jobs.JOBS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            AirbyteMetadata.AIRBYTE_METADATA,
            Attempts.ATTEMPTS,
            Jobs.JOBS);
    }
}
