#!/bin/bash

main () {
  local stream=$1
  for zendesk_talk in source-zendesk-talk source-zendesk-talk-two; do
    printf "fetching $stream with $zendesk_talk... "
    timeout 10 poetry run $zendesk_talk read --config secrets/config.json --catalog single-stream-catalogs/${stream}.json | tail > /tmp/migration/${zendesk_talk}_${stream}
    if [[ $? -eq 0 ]]; then
      echo "✅"
    else
      echo "⏱️ "
    fi
  done
}

main "$@"
