package io.airbyte.integrations.source.postgres;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import io.airbyte.commons.json.Jsons;
import io.airbyte.commons.util.AutoCloseableIterator;
import io.airbyte.protocol.models.v0.AirbyteMessage;
import io.airbyte.protocol.models.v0.ConfiguredAirbyteCatalog;
import java.time.Duration;
import java.time.Instant;
import java.util.concurrent.atomic.AtomicInteger;

public class ProfilerTest {

  public static void main(String[] args) throws Exception {
    Thread.sleep(60 * 1000);
    Instant startTime = Instant.now();
    System.out.println("START_TIME: " + startTime);
    PostgresSource postgresSource = new PostgresSource();
    JsonNode deserializeConfig = get200MUserConfig();

    String catalog = get200MUsersCatalogString();

    ConfiguredAirbyteCatalog configuredAirbyteCatalog = Jsons.deserialize(catalog, ConfiguredAirbyteCatalog.class);

    System.out.println();

    AtomicInteger d = new AtomicInteger(0);
    try (final AutoCloseableIterator<AirbyteMessage> messageIterator = postgresSource.read(deserializeConfig, configuredAirbyteCatalog, null)) {
      messageIterator.forEachRemaining(c -> {
        d.incrementAndGet();
      });
    }

    Instant endTime = Instant.now();
    System.out.println("END_TIME: " + endTime);
    System.out.println("TOTAL_TIME_TAKEN_IN_SECONDS: " + Duration.between(startTime, endTime).toSeconds());
    System.out.println("Total records read" + d.get());
  }

  private static JsonNode get200MUserConfig() {
    return null;
  }

  private static JsonNode get10MUserConfig() {
    return null;
  }

  private static JsonNode get1MUserConfig() {
    return null;
  }


  private static String get200MUsersCatalogString() {
    return "{\n"
        + "    \"streams\": [\n"
        + "        {\n"
        + "            \"stream\": {\n"
        + "                \"name\": \"purchases\",\n"
        + "                \"namespace\": \"200m_users\",\n"
        + "                \"json_schema\": {\n"
        + "                    \"type\": \"object\",\n"
        + "                    \"properties\": {\n"
        + "                        \"id\": {\n"
        + "                            \"type\": \"number\",\n"
        + "                            \"airbyte_type\": \"integer\"\n"
        + "                        },\n"
        + "                        \"user_id\": {\n"
        + "                            \"type\": \"number\",\n"
        + "                            \"airbyte_type\": \"integer\"\n"
        + "                        },\n"
        + "                        \"product_id\": {\n"
        + "                            \"type\": \"number\",\n"
        + "                            \"airbyte_type\": \"integer\"\n"
        + "                        },\n"
        + "                        \"returned_at\": {\n"
        + "                            \"type\": \"string\",\n"
        + "                            \"format\": \"date-time\",\n"
        + "                            \"airbyte_type\": \"timestamp_with_timezone\"\n"
        + "                        },\n"
        + "                        \"purchased_at\": {\n"
        + "                            \"type\": \"string\",\n"
        + "                            \"format\": \"date-time\",\n"
        + "                            \"airbyte_type\": \"timestamp_with_timezone\"\n"
        + "                        },\n"
        + "                        \"added_to_cart_at\": {\n"
        + "                            \"type\": \"string\",\n"
        + "                            \"format\": \"date-time\",\n"
        + "                            \"airbyte_type\": \"timestamp_with_timezone\"\n"
        + "                        }\n"
        + "                    }\n"
        + "                },\n"
        + "                \"default_cursor_field\": [],\n"
        + "                \"supported_sync_modes\": [\n"
        + "                    \"full_refresh\",\n"
        + "                    \"incremental\"\n"
        + "                ],\n"
        + "                \"source_defined_primary_key\": [\n"
        + "                    [\n"
        + "                        \"id\"\n"
        + "                    ]\n"
        + "                ]\n"
        + "            },\n"
        + "            \"sync_mode\": \"incremental\",\n"
        + "            \"primary_key\": [\n"
        + "                [\n"
        + "                    \"id\"\n"
        + "                ]\n"
        + "            ],\n"
        + "            \"cursor_field\": [\n"
        + "                \"id\"\n"
        + "            ],\n"
        + "            \"destination_sync_mode\": \"append\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"stream\": {\n"
        + "                \"name\": \"users\",\n"
        + "                \"namespace\": \"200m_users\",\n"
        + "                \"json_schema\": {\n"
        + "                    \"type\": \"object\",\n"
        + "                    \"properties\": {\n"
        + "                        \"id\": {\n"
        + "                            \"type\": \"number\",\n"
        + "                            \"airbyte_type\": \"integer\"\n"
        + "                        },\n"
        + "                        \"age\": {\n"
        + "                            \"type\": \"number\",\n"
        + "                            \"airbyte_type\": \"integer\"\n"
        + "                        },\n"
        + "                        \"name\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"email\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"title\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"gender\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"height\": {\n"
        + "                            \"type\": \"number\"\n"
        + "                        },\n"
        + "                        \"weight\": {\n"
        + "                            \"type\": \"number\",\n"
        + "                            \"airbyte_type\": \"integer\"\n"
        + "                        },\n"
        + "                        \"language\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"telephone\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"blood_type\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"created_at\": {\n"
        + "                            \"type\": \"string\",\n"
        + "                            \"format\": \"date-time\",\n"
        + "                            \"airbyte_type\": \"timestamp_with_timezone\"\n"
        + "                        },\n"
        + "                        \"occupation\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"updated_at\": {\n"
        + "                            \"type\": \"string\",\n"
        + "                            \"format\": \"date-time\",\n"
        + "                            \"airbyte_type\": \"timestamp_with_timezone\"\n"
        + "                        },\n"
        + "                        \"nationality\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"academic_degree\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        }\n"
        + "                    }\n"
        + "                },\n"
        + "                \"default_cursor_field\": [],\n"
        + "                \"supported_sync_modes\": [\n"
        + "                    \"full_refresh\",\n"
        + "                    \"incremental\"\n"
        + "                ],\n"
        + "                \"source_defined_primary_key\": [\n"
        + "                    [\n"
        + "                        \"id\"\n"
        + "                    ]\n"
        + "                ]\n"
        + "            },\n"
        + "            \"sync_mode\": \"incremental\",\n"
        + "            \"primary_key\": [\n"
        + "                [\n"
        + "                    \"id\"\n"
        + "                ]\n"
        + "            ],\n"
        + "            \"cursor_field\": [\n"
        + "                \"updated_at\"\n"
        + "            ],\n"
        + "            \"destination_sync_mode\": \"append\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"stream\": {\n"
        + "                \"name\": \"products\",\n"
        + "                \"namespace\": \"200m_users\",\n"
        + "                \"json_schema\": {\n"
        + "                    \"type\": \"object\",\n"
        + "                    \"properties\": {\n"
        + "                        \"id\": {\n"
        + "                            \"type\": \"number\",\n"
        + "                            \"airbyte_type\": \"integer\"\n"
        + "                        },\n"
        + "                        \"make\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"year\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"model\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"price\": {\n"
        + "                            \"type\": \"number\"\n"
        + "                        },\n"
        + "                        \"created_at\": {\n"
        + "                            \"type\": \"string\",\n"
        + "                            \"format\": \"date-time\",\n"
        + "                            \"airbyte_type\": \"timestamp_with_timezone\"\n"
        + "                        }\n"
        + "                    }\n"
        + "                },\n"
        + "                \"default_cursor_field\": [],\n"
        + "                \"supported_sync_modes\": [\n"
        + "                    \"full_refresh\",\n"
        + "                    \"incremental\"\n"
        + "                ],\n"
        + "                \"source_defined_primary_key\": [\n"
        + "                    [\n"
        + "                        \"id\"\n"
        + "                    ]\n"
        + "                ]\n"
        + "            },\n"
        + "            \"sync_mode\": \"incremental\",\n"
        + "            \"primary_key\": [\n"
        + "                [\n"
        + "                    \"id\"\n"
        + "                ]\n"
        + "            ],\n"
        + "            \"cursor_field\": [\n"
        + "                \"created_at\"\n"
        + "            ],\n"
        + "            \"destination_sync_mode\": \"append\"\n"
        + "        }\n"
        + "    ]\n"
        + "}";
  }

  private static String get10MUsersCatalogString() {
    return "{\n"
        + "    \"streams\": [\n"
        + "        {\n"
        + "            \"stream\": {\n"
        + "                \"name\": \"purchases\",\n"
        + "                \"namespace\": \"10m_users\",\n"
        + "                \"json_schema\": {\n"
        + "                    \"type\": \"object\",\n"
        + "                    \"properties\": {\n"
        + "                        \"id\": {\n"
        + "                            \"type\": \"number\",\n"
        + "                            \"airbyte_type\": \"integer\"\n"
        + "                        },\n"
        + "                        \"user_id\": {\n"
        + "                            \"type\": \"number\",\n"
        + "                            \"airbyte_type\": \"integer\"\n"
        + "                        },\n"
        + "                        \"product_id\": {\n"
        + "                            \"type\": \"number\",\n"
        + "                            \"airbyte_type\": \"integer\"\n"
        + "                        },\n"
        + "                        \"returned_at\": {\n"
        + "                            \"type\": \"string\",\n"
        + "                            \"format\": \"date-time\",\n"
        + "                            \"airbyte_type\": \"timestamp_with_timezone\"\n"
        + "                        },\n"
        + "                        \"purchased_at\": {\n"
        + "                            \"type\": \"string\",\n"
        + "                            \"format\": \"date-time\",\n"
        + "                            \"airbyte_type\": \"timestamp_with_timezone\"\n"
        + "                        },\n"
        + "                        \"added_to_cart_at\": {\n"
        + "                            \"type\": \"string\",\n"
        + "                            \"format\": \"date-time\",\n"
        + "                            \"airbyte_type\": \"timestamp_with_timezone\"\n"
        + "                        }\n"
        + "                    }\n"
        + "                },\n"
        + "                \"default_cursor_field\": [],\n"
        + "                \"supported_sync_modes\": [\n"
        + "                    \"full_refresh\",\n"
        + "                    \"incremental\"\n"
        + "                ],\n"
        + "                \"source_defined_primary_key\": [\n"
        + "                    [\n"
        + "                        \"id\"\n"
        + "                    ]\n"
        + "                ]\n"
        + "            },\n"
        + "            \"sync_mode\": \"incremental\",\n"
        + "            \"primary_key\": [\n"
        + "                [\n"
        + "                    \"id\"\n"
        + "                ]\n"
        + "            ],\n"
        + "            \"cursor_field\": [\n"
        + "                \"id\"\n"
        + "            ],\n"
        + "            \"destination_sync_mode\": \"append\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"stream\": {\n"
        + "                \"name\": \"users\",\n"
        + "                \"namespace\": \"10m_users\",\n"
        + "                \"json_schema\": {\n"
        + "                    \"type\": \"object\",\n"
        + "                    \"properties\": {\n"
        + "                        \"id\": {\n"
        + "                            \"type\": \"number\",\n"
        + "                            \"airbyte_type\": \"integer\"\n"
        + "                        },\n"
        + "                        \"age\": {\n"
        + "                            \"type\": \"number\",\n"
        + "                            \"airbyte_type\": \"integer\"\n"
        + "                        },\n"
        + "                        \"name\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"email\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"title\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"gender\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"height\": {\n"
        + "                            \"type\": \"number\"\n"
        + "                        },\n"
        + "                        \"weight\": {\n"
        + "                            \"type\": \"number\",\n"
        + "                            \"airbyte_type\": \"integer\"\n"
        + "                        },\n"
        + "                        \"language\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"telephone\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"blood_type\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"created_at\": {\n"
        + "                            \"type\": \"string\",\n"
        + "                            \"format\": \"date-time\",\n"
        + "                            \"airbyte_type\": \"timestamp_with_timezone\"\n"
        + "                        },\n"
        + "                        \"occupation\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"updated_at\": {\n"
        + "                            \"type\": \"string\",\n"
        + "                            \"format\": \"date-time\",\n"
        + "                            \"airbyte_type\": \"timestamp_with_timezone\"\n"
        + "                        },\n"
        + "                        \"nationality\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"academic_degree\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        }\n"
        + "                    }\n"
        + "                },\n"
        + "                \"default_cursor_field\": [],\n"
        + "                \"supported_sync_modes\": [\n"
        + "                    \"full_refresh\",\n"
        + "                    \"incremental\"\n"
        + "                ],\n"
        + "                \"source_defined_primary_key\": [\n"
        + "                    [\n"
        + "                        \"id\"\n"
        + "                    ]\n"
        + "                ]\n"
        + "            },\n"
        + "            \"sync_mode\": \"incremental\",\n"
        + "            \"primary_key\": [\n"
        + "                [\n"
        + "                    \"id\"\n"
        + "                ]\n"
        + "            ],\n"
        + "            \"cursor_field\": [\n"
        + "                \"updated_at\"\n"
        + "            ],\n"
        + "            \"destination_sync_mode\": \"append\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"stream\": {\n"
        + "                \"name\": \"products\",\n"
        + "                \"namespace\": \"10m_users\",\n"
        + "                \"json_schema\": {\n"
        + "                    \"type\": \"object\",\n"
        + "                    \"properties\": {\n"
        + "                        \"id\": {\n"
        + "                            \"type\": \"number\",\n"
        + "                            \"airbyte_type\": \"integer\"\n"
        + "                        },\n"
        + "                        \"make\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"year\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"model\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"price\": {\n"
        + "                            \"type\": \"number\"\n"
        + "                        },\n"
        + "                        \"created_at\": {\n"
        + "                            \"type\": \"string\",\n"
        + "                            \"format\": \"date-time\",\n"
        + "                            \"airbyte_type\": \"timestamp_with_timezone\"\n"
        + "                        }\n"
        + "                    }\n"
        + "                },\n"
        + "                \"default_cursor_field\": [],\n"
        + "                \"supported_sync_modes\": [\n"
        + "                    \"full_refresh\",\n"
        + "                    \"incremental\"\n"
        + "                ],\n"
        + "                \"source_defined_primary_key\": [\n"
        + "                    [\n"
        + "                        \"id\"\n"
        + "                    ]\n"
        + "                ]\n"
        + "            },\n"
        + "            \"sync_mode\": \"incremental\",\n"
        + "            \"primary_key\": [\n"
        + "                [\n"
        + "                    \"id\"\n"
        + "                ]\n"
        + "            ],\n"
        + "            \"cursor_field\": [\n"
        + "                \"created_at\"\n"
        + "            ],\n"
        + "            \"destination_sync_mode\": \"append\"\n"
        + "        }\n"
        + "    ]\n"
        + "}";
  }


  private static String get1MUsersCatalogString() {
    return "{\n"
        + "    \"streams\": [\n"
        + "        {\n"
        + "            \"stream\": {\n"
        + "                \"name\": \"purchases\",\n"
        + "                \"namespace\": \"1m_users\",\n"
        + "                \"json_schema\": {\n"
        + "                    \"type\": \"object\",\n"
        + "                    \"properties\": {\n"
        + "                        \"id\": {\n"
        + "                            \"type\": \"number\",\n"
        + "                            \"airbyte_type\": \"integer\"\n"
        + "                        },\n"
        + "                        \"user_id\": {\n"
        + "                            \"type\": \"number\",\n"
        + "                            \"airbyte_type\": \"integer\"\n"
        + "                        },\n"
        + "                        \"product_id\": {\n"
        + "                            \"type\": \"number\",\n"
        + "                            \"airbyte_type\": \"integer\"\n"
        + "                        },\n"
        + "                        \"returned_at\": {\n"
        + "                            \"type\": \"string\",\n"
        + "                            \"format\": \"date-time\",\n"
        + "                            \"airbyte_type\": \"timestamp_with_timezone\"\n"
        + "                        },\n"
        + "                        \"purchased_at\": {\n"
        + "                            \"type\": \"string\",\n"
        + "                            \"format\": \"date-time\",\n"
        + "                            \"airbyte_type\": \"timestamp_with_timezone\"\n"
        + "                        },\n"
        + "                        \"added_to_cart_at\": {\n"
        + "                            \"type\": \"string\",\n"
        + "                            \"format\": \"date-time\",\n"
        + "                            \"airbyte_type\": \"timestamp_with_timezone\"\n"
        + "                        }\n"
        + "                    }\n"
        + "                },\n"
        + "                \"default_cursor_field\": [],\n"
        + "                \"supported_sync_modes\": [\n"
        + "                    \"full_refresh\",\n"
        + "                    \"incremental\"\n"
        + "                ],\n"
        + "                \"source_defined_primary_key\": [\n"
        + "                    [\n"
        + "                        \"id\"\n"
        + "                    ]\n"
        + "                ]\n"
        + "            },\n"
        + "            \"sync_mode\": \"incremental\",\n"
        + "            \"primary_key\": [\n"
        + "                [\n"
        + "                    \"id\"\n"
        + "                ]\n"
        + "            ],\n"
        + "            \"cursor_field\": [\n"
        + "                \"id\"\n"
        + "            ],\n"
        + "            \"destination_sync_mode\": \"append\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"stream\": {\n"
        + "                \"name\": \"users\",\n"
        + "                \"namespace\": \"1m_users\",\n"
        + "                \"json_schema\": {\n"
        + "                    \"type\": \"object\",\n"
        + "                    \"properties\": {\n"
        + "                        \"id\": {\n"
        + "                            \"type\": \"number\",\n"
        + "                            \"airbyte_type\": \"integer\"\n"
        + "                        },\n"
        + "                        \"age\": {\n"
        + "                            \"type\": \"number\",\n"
        + "                            \"airbyte_type\": \"integer\"\n"
        + "                        },\n"
        + "                        \"name\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"email\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"title\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"gender\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"height\": {\n"
        + "                            \"type\": \"number\"\n"
        + "                        },\n"
        + "                        \"weight\": {\n"
        + "                            \"type\": \"number\",\n"
        + "                            \"airbyte_type\": \"integer\"\n"
        + "                        },\n"
        + "                        \"language\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"telephone\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"blood_type\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"created_at\": {\n"
        + "                            \"type\": \"string\",\n"
        + "                            \"format\": \"date-time\",\n"
        + "                            \"airbyte_type\": \"timestamp_with_timezone\"\n"
        + "                        },\n"
        + "                        \"occupation\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"updated_at\": {\n"
        + "                            \"type\": \"string\",\n"
        + "                            \"format\": \"date-time\",\n"
        + "                            \"airbyte_type\": \"timestamp_with_timezone\"\n"
        + "                        },\n"
        + "                        \"nationality\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"academic_degree\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        }\n"
        + "                    }\n"
        + "                },\n"
        + "                \"default_cursor_field\": [],\n"
        + "                \"supported_sync_modes\": [\n"
        + "                    \"full_refresh\",\n"
        + "                    \"incremental\"\n"
        + "                ],\n"
        + "                \"source_defined_primary_key\": [\n"
        + "                    [\n"
        + "                        \"id\"\n"
        + "                    ]\n"
        + "                ]\n"
        + "            },\n"
        + "            \"sync_mode\": \"incremental\",\n"
        + "            \"primary_key\": [\n"
        + "                [\n"
        + "                    \"id\"\n"
        + "                ]\n"
        + "            ],\n"
        + "            \"cursor_field\": [\n"
        + "                \"updated_at\"\n"
        + "            ],\n"
        + "            \"destination_sync_mode\": \"append\"\n"
        + "        },\n"
        + "        {\n"
        + "            \"stream\": {\n"
        + "                \"name\": \"products\",\n"
        + "                \"namespace\": \"1m_users\",\n"
        + "                \"json_schema\": {\n"
        + "                    \"type\": \"object\",\n"
        + "                    \"properties\": {\n"
        + "                        \"id\": {\n"
        + "                            \"type\": \"number\",\n"
        + "                            \"airbyte_type\": \"integer\"\n"
        + "                        },\n"
        + "                        \"make\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"year\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"model\": {\n"
        + "                            \"type\": \"string\"\n"
        + "                        },\n"
        + "                        \"price\": {\n"
        + "                            \"type\": \"number\"\n"
        + "                        },\n"
        + "                        \"created_at\": {\n"
        + "                            \"type\": \"string\",\n"
        + "                            \"format\": \"date-time\",\n"
        + "                            \"airbyte_type\": \"timestamp_with_timezone\"\n"
        + "                        }\n"
        + "                    }\n"
        + "                },\n"
        + "                \"default_cursor_field\": [],\n"
        + "                \"supported_sync_modes\": [\n"
        + "                    \"full_refresh\",\n"
        + "                    \"incremental\"\n"
        + "                ],\n"
        + "                \"source_defined_primary_key\": [\n"
        + "                    [\n"
        + "                        \"id\"\n"
        + "                    ]\n"
        + "                ]\n"
        + "            },\n"
        + "            \"sync_mode\": \"incremental\",\n"
        + "            \"primary_key\": [\n"
        + "                [\n"
        + "                    \"id\"\n"
        + "                ]\n"
        + "            ],\n"
        + "            \"cursor_field\": [\n"
        + "                \"created_at\"\n"
        + "            ],\n"
        + "            \"destination_sync_mode\": \"append\"\n"
        + "        }\n"
        + "    ]\n"
        + "}";
  }

}
