acceptance_tests:
  spec:
    tests:
      - config_path: secrets/config.json
  connection:
    tests:
      - config_path: secrets/config.json
        status: succeed
      - config_path: integration_tests/invalid_config.json
        status: failed
  basic_read:
    tests:
      - config_path: secrets/config.json
        configured_catalog_path: integration_tests/configured_catalog.json
