import { initialSetupCompleted } from "commands/workspaces";
import { goToSourcePage, openNewSourceForm } from "pages/sourcePage";
import { selectServiceType } from "pages/createConnectorPage";
import { goToDestinationPage, openNewDestinationForm } from "pages/destinationPage";

describe("Source Doc panel", () => {
    [ { "name" : "AlloyDB for PostgreSQL", "id" :"alloydb-for-postgresql" }, //??? cannot click
    { "name" : "Amazon Ads", "id" :"amazon-ads" },
    { "name" : "Chargebee", "id" :"chargebee" },
    { "name" : "Facebook Marketing", "id" :"facebook-marketing" },
    { "name" : "File", "id" :"files" },
    { "name" : "Freshdesk", "id" :"freshdesk" },
    { "name" : "GitHub", "id" :"github" },
    { "name" : "Google Ads", "id" :"google-ads" },
    { "name" : "Google Analytics (Universal Analytics)", "id" :"google-analytics-universal-analytics" },
    { "name" : "Google Search Console", "id" :"google-search-console" },
    { "name" : "Harvest", "id" :"harvest" },
    { "name" : "HubSpot", "id" :"hubspot" },
    { "name" : "Instagram", "id" :"instagram" },
    { "name" : "Intercom", "id" :"intercom" },
    { "name" : "Klaviyo", "id" :"klaviyo" },
    { "name" : "LinkedIn Ads", "id" :"linkedin-ads" },
    { "name" : "Mixpanel", "id" :"mixpanel" },
    { "name" : "Paypal Transaction", "id" :"paypal-transaction" },
    { "name" : "Pinterest", "id" :"pinterest" },
    { "name" : "Postgres", "id" :"postgres" },
    { "name" : "S3", "id" :"amazon-s3" },
    { "name" : "Slack", "id" :"slack" },
    { "name" : "SurveyMonkey", "id" :"surveymonkey" },
    { "name" : "TikTok Marketing", "id" :"tiktok-marketing" },
    { "name" : "Twilio", "id" :"twilio" },
    { "name" : "Zendesk Chat", "id" :"zendesk-chat" },
    { "name" : "Zendesk Support", "id" :"zendesk-support" },
    { "name" : "Freshcaller", "id" :"freshcaller" },
    { "name" : "Amplitude", "id" :"amplitude" },
    { "name" : "Bing Ads", "id" :"bing-ads" },
    { "name" : "Google Sheets", "id" :"google-sheets" },
    { "name" : "Greenhouse", "id" :"greenhouse" },
    { "name" : "Iterable", "id" :"iterable" },
    { "name" : "Mailchimp", "id" :"mailchimp" },
    { "name" : "Marketo", "id" :"marketo" },
    { "name" : "Notion", "id" :"notion" },
    { "name" : "Recharge", "id" :"recharge" },
    { "name" : "Salesforce", "id" :"salesforce" },
    { "name" : "Sentry", "id" :"sentry" },
    { "name" : "Snapchat Marketing", "id" :"snapchat-marketing" },
    { "name" : "Stripe", "id" :"stripe" },
    { "name" : "Zendesk Talk", "id" :"zendesk-talk" },
    { "name" : "Asana", "id" :"asana" },
    { "name" : "MySQL", "id" :"mysql" },
    { "name" : "Sendgrid", "id" :"sendgrid" },
    { "name" : "Smartsheets", "id" :"smartsheets" },
    { "name" : "YouTube Analytics", "id" :"youtube-analytics" },
    { "name" : "ActiveCampaign", "id" :"activecampaign" },
    { "name" : "Adjust", "id" :"airbyte-source-connector-for-adjust" },
    { "name" : "Airtable", "id" :"airtable" },
    { "name" : "Amazon Seller Partner", "id" :"amazon-seller-partner" },
    { "name" : "Amazon SQS", "id" :"amazon-sqs" },
    { "name" : "Apify Dataset", "id" :"apify-dataset" },
    { "name" : "Appfollow", "id" :"appfollow" },
    { "name" : "Appstore", "id" :"appstore" },
    { "name" : "Ashby", "id" :"ashby" },
    { "name" : "Auth0", "id" :"auth0" },
    { "name" : "AWS CloudTrail", "id" :"aws-cloudtrail" },
    { "name" : "Azure Table Storage", "id" :"azure-table-storage" },
    { "name" : "BambooHR", "id" :"bamboo-hr" },
    { "name" : "BigCommerce", "id" :"bigcommerce" },
    { "name" : "BigQuery", "id" :"bigquery" },
    { "name" : "Braintree", "id" :"braintree" },
    { "name" : "Cart.com", "id" :"cartcom" },
    { "name" : "Chargify", "id" :"chargify" },
    { "name" : "Chartmogul", "id" :"chartmogul" },
    { "name" : "ClickHouse", "id" :"clickhouse" },
    { "name" : "Clockify", "id" :"clockify" }, //??? no doc panel
    { "name" : "Close.com", "id" :"closecom" },
    { "name" : "Cockroachdb", "id" :"cockroachdb" },
    { "name" : "Coin API", "id" :"coinapi" },
    { "name" : "Commercetools", "id" :"commercetools" },
    { "name" : "Confluence", "id" :"confluence" },
    { "name" : "Courier", "id" :"courier" },
    { "name" : "Customer.io", "id" :"customerio" },
    { "name" : "Delighted", "id" :"delighted" },
    { "name" : "Dixa", "id" :"dixa" },
    { "name" : "Dockerhub", "id" :"dockerhub" },
    { "name" : "Drift", "id" :"drift" },
    { "name" : "DV 360", "id" :"dv-360" }, //???? no doc panel
    { "name" : "E2E Testing", "id" :"end-to-end-testing-source" },
    { "name" : "Elasticsearch", "id" :"elasticsearch" },
    { "name" : "Exchange Rates API", "id" :"exchange-rates-api" }, //??cannot click
    { "name" : "Facebook Pages", "id" :"facebook-pages" },
    { "name" : "Faker", "id" :"faker" },
    { "name" : "Fauna", "id" :"fauna" },
    { "name" : "Firebolt", "id" :"firebolt" },
    { "name" : "Flexport", "id" :"flexport" },
    { "name" : "Freshsales", "id" :"freshsales" },
    { "name" : "Freshservice", "id" :"freshservice" },
    { "name" : "Gitlab", "id" :"gitlab" },
    { "name" : "Glassfrog", "id" :"glassfrog" },
    { "name" : "GoCardless", "id" :"gocardless" },
    { "name" : "Google Analytics 4 (GA4)", "id" :"google-analytics-4-ga4" },
    { "name" : "Google Directory", "id" :"google-directory" },
    { "name" : "Google Workspace Admin Reports", "id" :"google-workspace-admin-reports" },
    { "name" : "Gutendex", "id" :"gutendex" },
    { "name" : "Harness", "id" :"harness" },
    { "name" : "Hellobaton", "id" :"baton" },
    { "name" : "Hubplanner", "id" :"hubplanner" },
    { "name" : "IBM Db2", "id" :"db2" },
    { "name" : "Insightly", "id" :"insightly" },
    { "name" : "Jenkins", "id" :"jenkins" },
    { "name" : "Jira", "id" :"jira" },
    { "name" : "Kafka", "id" :"kafka" },
    { "name" : "Kustomer", "id" :"kustomer" },
    { "name" : "Kyriba", "id" :"kyriba" },
    { "name" : "Lemlist", "id" :"lemlist" },
    { "name" : "Lever Hiring", "id" :"lever-hiring" },
    { "name" : "LinkedIn Pages", "id" :"linkedin-pages" },
    { "name" : "Linnworks", "id" :"linnworks" },
    { "name" : "Lokalise", "id" :"lokalise" },
    { "name" : "Looker", "id" :"looker" },
    { "name" : "MailerLite", "id" :"activecampaign" },
    { "name" : "Mailgun", "id" :"mailgun" }, //???? no doc panel
    { "name" : "Mailjet Mail", "id" :"mailjet---mail-api" },
    { "name" : "Metabase", "id" :"metabase" },
    { "name" : "Microsoft SQL Server (MSSQL)", "id" :"microsoft-sql-server-mssql" },
    { "name" : "Microsoft teams", "id" :"microsoft-teams" },
    { "name" : "Monday", "id" :"monday" },
    { "name" : "MongoDb", "id" :"mongo-db" },
    { "name" : "My Hours", "id" :"my-hours" },
    { "name" : "NASA", "id" :"nasa" },
    { "name" : "Netsuite", "id" :"oracle-netsuite" },
    { "name" : "News API", "id" :"news-api" },
    { "name" : "Okta", "id" :"okta" },
    { "name" : "OneSignal", "id" :"onesignal" },
    { "name" : "OpenWeather", "id" :"openweather" },
    { "name" : "Oracle DB", "id" :"oracle-db" },
    { "name" : "Orb", "id" :"orb" },
    { "name" : "Orbit", "id" :"orbit" },
    { "name" : "Oura", "id" :"oura" },
    { "name" : "Outreach", "id" :"outreach" },
    { "name" : "PagerDuty", "id" :"pagerduty" },
    { "name" : "Paystack", "id" :"paystack" },
    { "name" : "PersistIq", "id" :"persistiq" },
    { "name" : "Pipedrive", "id" :"pipedrive" },
    { "name" : "Pivotal Tracker", "id" :"pivotal-tracker" },
    { "name" : "Plaid", "id" :"plaid" },
    { "name" : "PokeAPI", "id" :"pokéapi" },
    { "name" : "PostHog", "id" :"posthog" },
    { "name" : "Prestashop", "id" :"prestashop" },
    { "name" : "Primetric", "id" :"primetric" }, //????? PrestaShop
    { "name" : "Qualaroo", "id" :"qualaroo" },
    { "name" : "QuickBooks", "id" :"quickbooks" },
    { "name" : "RD Station Marketing", "id" :"rd-station-marketing" },
    { "name" : "Recurly", "id" :"recurly" },
    { "name" : "Redshift", "id" :"redshift" },
    { "name" : "Retently", "id" :"retently" },
    { "name" : "RKI Covid", "id" :"robert-koch-institut-covid" },
    { "name" : "SalesLoft", "id" :"salesloft" },
    { "name" : "SearchMetrics", "id" :"searchmetrics" },
    { "name" : "SFTP", "id" :"sftp" },
    { "name" : "SFTP Bulk", "id" :"sftp--bulk" },
    { "name" : "Shopify", "id" :"shopify" },
    { "name" : "Short.io", "id" :"shortio" },
    { "name" : "Snowflake", "id" :"snowflake" },
    { "name" : "Sonar Cloud", "id" :"sonar-cloud-api" },
    { "name" : "Square", "id" :"square" },
    { "name" : "Strava", "id" :"strava" },
    { "name" : "TalkDesk Explore", "id" :"talkdesk-explore" },
    { "name" : "Tempo", "id" :"tempo" },
    { "name" : "TiDB", "id" :"tidb" },
    { "name" : "Timely", "id" :"timely" },
    { "name" : "Trello", "id" :"trello" },
    { "name" : "TVMaze Schedule", "id" :"tvmaze-schedule" },
    { "name" : "Typeform", "id" :"typeform" },
    { "name" : "US Census", "id" :"us-census-api" },
    { "name" : "VictorOps", "id" :"victorops" },
    { "name" : "Webflow", "id" :"webflow" },
    { "name" : "Whisky Hunter", "id" :"whisky-hunter" },
    { "name" : "WooCommerce", "id" :"woocommerce" },
    { "name" : "Workable", "id" :"workable" },
    { "name" : "Wrike", "id" :"wrike" },
    { "name" : "xkcd", "id" :"xkcd" },
    { "name" : "Yandex Metrica", "id" :"yandex-metrica" },
    { "name" : "Zendesk Sunshine", "id" :"zendesk-sunshine" },
    { "name" : "Zenefits", "id" :"zenefits" },
    { "name" : "Zenloop", "id" :"zenloop" },
    { "name" : "ZohoCRM", "id" :"zoho-crm" },
    { "name" : "Zoom", "id" :"zoom" },
    { "name" : "Zuora", "id" :"zuora" } ]
    .forEach((connector) => {
    beforeEach(() => {
      initialSetupCompleted();
    });
  
    it("Check Doc panel for " + connector.name + " source", () => {
      goToSourcePage();
      openNewSourceForm();

      selectServiceType(connector.name);
  
      assert(cy.get(`h1[id="${connector.id}"]`));
    });
  });
});

describe("Destination Doc panel", () => {
    [ { "name" : "BigQuery", "id" :"alloydb-for-postgresql" },
    { "name" :  "S3", "id" :"s3" },
    { "name" : "Snowflake", "id" :"snowflake" },
    { "name" : "E2E Testing", "id" :"end-to-end-testing-source" },
    { "name" : "BigQuery (denormalized typed struct)", "id" :"bigquery" },
    { "name" : "Google Cloud Storage (GCS)", "id" :"google-cloud-storage-gcs" },
    { "name" : "Redshift", "id" :"redshift" },
    { "name" : "Amazon SQS", "id" :"amazon-sqs" },
    { "name" : "AWS Datalake", "id" :"aws-datalake" },
    { "name" : "Azure Blob Storage", "id" :"azureblobstorage" },
    { "name" : "Cassandra", "id" :"cassandra" },
    { "name" : "Chargify (Keen)", "id" :"keen" },
    { "name" : "Clickhouse", "id" :"clickhouse" },
    { "name" : "Cloudflare R2", "id" :"r2" },
    { "name" : "Databricks Lakehouse", "id" :"databricks-lakehouse" },
    { "name" : "DynamoDB", "id" :"dynamodb" },
    { "name" : "ElasticSearch", "id" :"elasticsearch" },
    { "name" : "Firebolt", "id" :"firebolt" },
    { "name" : "Google Firestore", "id" :"google-firestore" }, //???
    { "name" : "Google PubSub", "id" :"google-pubsub" },
    { "name" : "Google Sheets", "id" :"google-sheets" },
    { "name" : "Kafka", "id" :"kafka" },
    { "name" : "Kinesis", "id" :"kinesis" },
    { "name" : "Local CSV", "id" :"local-csv" },
    { "name" : "Local JSON", "id" :"local-json" },
    { "name" : "Local SQLite", "id" :"local-sqlite" }, //???
    { "name" : "MariaDB ColumnStore", "id" :"mariadb-columnstore" },
    { "name" : "MeiliSearch", "id" :"meilisearch" },
    { "name" : "MongoDB", "id" :"mongodb" },
    { "name" : "MQTT", "id" :"mqtt" },
    { "name" : "MS SQL Server", "id" :"mssql" },
    { "name" : "MySQL", "id" :"mysql" },
    { "name" : "Oracle", "id" :"oracle-db" },
    { "name" : "Postgres", "id" :"postgres" },
    { "name" : "Pulsar", "id" :"pulsar" },
    { "name" : "RabbitMQ", "id" :"rabbitmq" },
    { "name" : "Redis", "id" :"redis" },
    { "name" : "Rockset", "id" :"rockset" },
    { "name" : "Scylla", "id" :"scylla" },
    { "name" : "SFTP-JSON", "id" :"sftp-json" },
    { "name" : "Streamr", "id" :"streamr" },
    { "name" : "TiDB", "id" :"tidb" },
    { "name" : "YugabyteDB", "id" :"yugabytedb" }
  ]
    .forEach((connector) => {
    beforeEach(() => {
      initialSetupCompleted();
    });
  
    it("Check Doc panel for " + connector.name + " destination", () => {
      goToDestinationPage();
      openNewDestinationForm();

      selectServiceType(connector.name);
  
      assert(cy.get(`h1[id="${connector.id}"]`));
    });
});

});