FROM scratch

## TODO Add your dockerfile instructions here


# Airbyte's build system uses these labels to know what to name and tag the docker images produced by this Dockerfile.
LABEL io.airbyte.name=airbyte/source-{{dashCase name}}
LABEL io.airbyte.version=0.1.0
