/*
 * Copyright (c) 2024 Airbyte, Inc., all rights reserved.
 */

package io.airbyte.cdk.discover

/** Internal equivalent of a [io.airbyte.protocol.models.Field]. */
sealed interface FieldOrMetaField {
    val id: String
    val type: FieldType
}

/** Internal equivalent of [io.airbyte.protocol.models.Field] for values which come from the source itself, instead of being generated by the connector during its operation. */
data class Field(override val id: String, override val type: FieldType) : FieldOrMetaField

/** Internal equivalent of [io.airbyte.protocol.models.Field] for values which are generated by the connector itself during its operation, instead of coming from the source. */
interface MetaField : FieldOrMetaField {

    companion object {
        const val META_PREFIX = "_ab_"
        fun isMetaFieldID(id: String): Boolean = id.startsWith("_ab_")
    }
}

/** Convenience enum listing the [MetaField]s which are generated by all connectors. */
enum class CommonMetaField(override val type: FieldType) : MetaField {
    CDC_LSN(StringFieldType),
    CDC_UPDATED_AT(OffsetDateTimeFieldType),
    CDC_DELETED_AT(OffsetDateTimeFieldType);

    override val id: String
        get() = MetaField.META_PREFIX + name.lowercase()
}
