from datetime import datetime
from typing import Optional, Dict

from pydantic import BaseModel, Field


class Income(BaseModel):
    # fmt: off
    incomeId: Optional[int] = Field(description="Номер поставки")
    number: Optional[str] = Field(description="Номер УПД")
    date: Optional[datetime] = Field(description="Дата поступления")
    lastChangeDate: Optional[datetime] = Field(description="Дата и время обновления информации в сервисе")
    supplierArticle: Optional[str] = Field(description="Артикул продавца")
    techSize: Optional[str] = Field(description="Размер товара (пример S, M, L, XL, 42, 42-43)")
    barcode: Optional[str] = Field(description="Бар-код")
    quantity: Optional[int] = Field(description="Количество")
    totalPrice: Optional[float] = Field(description="Цена из УПД")
    dateClose: Optional[datetime] = Field(description="Дата принятия (закрытия) в WB")
    warehouseName: Optional[str] = Field(description="Название склада")
    nmId: Optional[int] = Field(description="Артикул WB")
    status: Optional[str] = Field(description="Текущий статус поставки")
    # fmt: on


class Stock(BaseModel):
    # fmt: off
    lastChangeDate: Optional[datetime] = Field(description="Дата и время обновления информации в сервисе")
    warehouseName: Optional[str] = Field(description="Название склада")
    supplierArticle: Optional[str] = Field(description="Артикул продавца")
    nmId: Optional[int] = Field(description="Артикул WB")
    barcode: Optional[str] = Field(description="Баркод")
    quantity: Optional[int] = Field(description="Количество, доступное для продажи (сколько можно добавить в корзину)")
    inWayToClient: Optional[int] = Field(description="В пути к клиенту")
    inWayFromClient: Optional[int] = Field(description="В пути от клиента")
    quantityFull: Optional[int] = Field(description="Полное (непроданное) количество, которое числится за складом")
    category: Optional[str] = Field(description="Категория")
    subject: Optional[str] = Field(description="Предмет")
    brand: Optional[str] = Field(description="Бренд")
    techSize: Optional[str] = Field(description="Размер")
    Price: Optional[float] = Field(description="Цена")
    Discount: Optional[float] = Field(description="Скидка")
    isSupply: Optional[bool] = Field(description="Договор поставки (внутренние технологические данные)")
    isRealization: Optional[bool] = Field(description="Договор реализации (внутренние технологические данные)")
    SCCode: Optional[str] = Field(description="Код контракта (внутренние технологические данные)")
    # fmt: on


class Order(BaseModel):
    # fmt: off
    gNumber: Optional[str] = Field(description="Номер заказа. Объединяет все позиции одного заказа")
    date: Optional[datetime] = Field(description="Дата и время заказа")
    lastChangeDate: Optional[datetime] = Field(description="Дата и время обновления информации в сервисе")
    supplierArticle: Optional[str] = Field(description="Артикул продавца")
    techSize: Optional[str] = Field(description="Размер товара (пример S, M, L, XL, 42, 42-43)")
    barcode: Optional[str] = Field(description="Бар-код")
    totalPrice: Optional[float] = Field(description="Цена до согласованной итоговой скидки/промо/спп")
    discountPercent: Optional[int] = Field(description="Согласованный итоговый дисконт")
    warehouseName: Optional[str] = Field(description="Название склада отгрузки")
    oblast: Optional[str] = Field(description="Область")
    incomeID: Optional[int] = Field(description="Номер поставки (от продавца на склад)")
    odid: Optional[int] = Field(description="Уникальный идентификатор позиции заказа. Может использоваться для поиска соответствия между заказами и продажами")
    nmId: Optional[int] = Field(description="Артикул WB")
    subject: Optional[str] = Field(description="Предмет")
    category: Optional[str] = Field(description="Категория")
    brand: Optional[str] = Field(description="Бренд")
    isCancel: Optional[bool] = Field(description="Отмена заказа. true - заказ отменен до оплаты.")
    cancel_dt: Optional[datetime] = Field(description='Дата и время отмены заказа. Если заказ не был отменен, то "0001-01-01T00:00:00"')
    sticker: Optional[str] = Field(description="Цифровое значение стикера, который клеится на товар в процессе сборки заказа по системе Маркетплейс")
    srid: Optional[str] = Field(description="Уникальный идентификатор заказа")
    orderType: Optional[str] = Field(description="Тип поступившего заказа")
    # fmt: on


class Sale(BaseModel):
    # fmt: off
    gNumber: Optional[str] = Field(description="Номер заказа. Объединяет все позиции одного заказа")
    date: Optional[datetime] = Field(description="Дата и время продажи")
    lastChangeDate: Optional[datetime] = Field(description="Дата и время обновления информации в сервисе")
    supplierArticle: Optional[str] = Field(description="Артикул продавца")
    techSize: Optional[str] = Field(description="Размер товара (пример S, M, L, XL, 42, 42-43)")
    barcode: Optional[str] = Field(description="Бар-код")
    totalPrice: Optional[float] = Field(description="Цена до согласованной скидки/промо/спп")
    discountPercent: Optional[int] = Field(description="Согласованный итоговый дисконт")
    isSupply: Optional[bool] = Field(description="Договор поставки")
    isRealization: Optional[bool] = Field(description="Договор реализации")
    promoCodeDiscount: Optional[float] = Field(description="Скидка по промокоду")
    warehouseName: Optional[str] = Field(description="Название склада отгрузки")
    countryName: Optional[str] = Field(description="Страна")
    oblastOkrugName: Optional[str] = Field(description="Округ")
    regionName: Optional[str] = Field(description="Регион")
    incomeID: Optional[int] = Field(description="Номер поставки (от продавца на склад)")
    saleID: Optional[str] = Field(description="Уникальный идентификатор продажи/возврата")
    odid: Optional[int] = Field(description="Уникальный идентификатор позиции заказа. Может использоваться для поиска соответствия между заказами и продажами")
    spp: Optional[float] = Field(description="Согласованная скидка постоянного покупателя")
    forPay: Optional[float] = Field(description="К перечислению продавцу")
    finishedPrice: Optional[float] = Field(description="Фактическая цена заказа с учетом всех скидок")
    priceWithDisc: Optional[float] = Field(description="Цена, от которой считается вознаграждение продавца forpay (с учетом всех согласованных скидок)")
    nmId: Optional[int] = Field(description="Артикул WB")
    subject: Optional[str] = Field(description="Предмет")
    category: Optional[str] = Field(description="Категория")
    brand: Optional[str] = Field(description="Бренд")
    IsStorno: Optional[int] = Field(description="Для сторно-операций 1, для остальных 0")
    sticker: Optional[str] = Field(description="Цифровое значение стикера, который клеится на товар в процессе сборки заказа по системе Маркетплейс")
    srid: Optional[str] = Field(description="Уникальный идентификатор заказа")
    # fmt: on


class ReportDetailByPeriod(BaseModel):
    # fmt: off
    realizationreport_id: Optional[int] = Field(description="Номер отчёта")
    date_from: Optional[datetime] = Field(description="Дата начала отчётного периода")
    date_to: Optional[datetime] = Field(description="Дата конца отчётного периода")
    create_dt: Optional[datetime] = Field(description="Дата формирования отчёта")
    currency_name: Optional[str] = Field(description="Валюта отчёта")
    suppliercontract_code: Optional[Dict] = Field(description="Договор")
    rrd_id: Optional[int] = Field(description="Номер строки")
    gi_id: Optional[int] = Field(description="Номер поставки")
    subject_name: Optional[str] = Field(description="Предмет")
    nm_id: Optional[int] = Field(description="Артикул WB")
    brand_name: Optional[str] = Field(description="Бренд")
    sa_name: Optional[str] = Field(description="Артикул продавца")
    ts_name: Optional[str] = Field(description="Размер")
    barcode: Optional[str] = Field(description="Баркод")
    doc_type_name: Optional[str] = Field(description="Тип документа")
    quantity: Optional[int] = Field(description="Количество")
    retail_price: Optional[float] = Field(description="Цена розничная")
    retail_amount: Optional[float] = Field(description="Сумма продаж (возвратов)")
    sale_percent: Optional[int] = Field(description="Согласованная скидка")
    commission_percent: Optional[float] = Field(description="Процент комиссии")
    office_name: Optional[str] = Field(description="Склад")
    supplier_oper_name: Optional[str] = Field(description="Обоснование для оплаты")
    order_dt: Optional[datetime] = Field(description="Дата заказа")
    sale_dt: Optional[datetime] = Field(description="Дата продажи")
    rr_dt: Optional[datetime] = Field(description="Дата операции")
    shk_id: Optional[int] = Field(description="Штрих-код")
    retail_price_withdisc_rub: Optional[float] = Field(description="Цена розничная с учетом согласованной скидки")
    delivery_amount: Optional[int] = Field(description="Количество доставок")
    return_amount: Optional[int] = Field(description="Количество возвратов")
    delivery_rub: Optional[float] = Field(description="Стоимость логистики")
    gi_box_type_name: Optional[str] = Field(description="Тип коробов")
    product_discount_for_report: Optional[float] = Field(description="Согласованный продуктовый дисконт")
    supplier_promo: Optional[float] = Field(description="Промокод")
    rid: Optional[int] = Field(description="Уникальный идентификатор заказа")
    ppvz_spp_prc: Optional[float] = Field(description="Скидка постоянного покупателя")
    ppvz_kvw_prc_base: Optional[float] = Field(description="Размер кВВ без НДС, % базовый")
    ppvz_kvw_prc: Optional[float] = Field(description="Итоговый кВВ без НДС, %")
    sup_rating_prc_up: Optional[float] = Field(description="Размер снижения кВВ из-за рейтинга")
    is_kgvp_v2: Optional[float] = Field(description="Размер снижения кВВ из-за акции")
    ppvz_sales_commission: Optional[float] = Field(description="Вознаграждение с продаж до вычета услуг поверенного, без НДС")
    ppvz_for_pay: Optional[float] = Field(description="К перечислению продавцу за реализованный товар")
    ppvz_reward: Optional[float] = Field(description="Возмещение за выдачу и возврат товаров на ПВЗ")
    acquiring_fee: Optional[float] = Field(description="Возмещение издержек по эквайрингу")
    acquiring_bank: Optional[str] = Field(description="Наименование банка-эквайера")
    ppvz_vw: Optional[float] = Field(description="Вознаграждение WB без НДС")
    ppvz_vw_nds: Optional[float] = Field(description="НДС с вознаграждения WB")
    ppvz_office_id: Optional[int] = Field(description="Номер офиса")
    ppvz_office_name: Optional[str] = Field(description="Наименование офиса доставки")
    ppvz_supplier_id: Optional[int] = Field(description="Номер партнера")
    ppvz_supplier_name: Optional[str] = Field(description="Партнер")
    ppvz_inn: Optional[str] = Field(description="ИНН партнера")
    declaration_number: Optional[str] = Field(description="Номер таможенной декларации")
    bonus_type_name: Optional[str] = Field(description="Обоснование штрафов и доплат")
    sticker_id: Optional[str] = Field(description='Цифровое значение стикера, который клеится на товар в процессе сборки заказа по схеме "Маркетплейс"')
    site_country: Optional[str] = Field(description="Страна продажи")
    penalty: Optional[float] = Field(description="Штрафы")
    additional_payment: Optional[float] = Field(description="Доплаты")
    rebill_logistic_cost: Optional[float] = Field(description="Возмещение издержек по перевозке")
    rebill_logistic_org: Optional[str] = Field(description="Организатор перевозки")
    kiz: Optional[str] = Field(description="Код маркировки")
    srid: Optional[str] = Field(description="Уникальный идентификатор заказа")
    # fmt: on
