# Migrated from airbyte-ci/connectors/base_images/README.md

# https://hub.docker.com/_/python/tags?name=3.11.11-slim-bookworm
ARG BASE_IMAGE=docker.io/python:3.11.11-slim-bookworm@sha256:081075da77b2b55c23c088251026fb69a7b2bf92471e491ff5fd75c192fd38e5
FROM ${BASE_IMAGE}

RUN ln -snf /usr/share/zoneinfo/Etc/UTC /etc/localtime

# Set-up groups, users, and directories
RUN adduser --uid 1000 --system --group --no-create-home airbyte && \
    mkdir --mode 755 /custom_cache && \
    mkdir --mode 755 /airbyte && \
    chown airbyte:airbyte /airbyte

ENV PIP_CACHE_DIR=/custom_cache/pip
RUN pip install --upgrade pip==24.0 setuptools==70.0.0

ENV POETRY_VIRTUALENVS_CREATE=false
ENV POETRY_VIRTUALENVS_IN_PROJECT=false
ENV POETRY_NO_INTERACTION=1

RUN pip install poetry==1.8.4
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get dist-upgrade -y && \
    apt-get clean
RUN apt-get install -y socat=1.7.4.4-2
RUN apt-get update && \
    apt-get install -y \
        tesseract-ocr=5.3.0-2 \
        poppler-utils=22.12.0-2+b1

RUN mkdir -p 755 /usr/share/nltk_data

# Dummy change (revert-me)
