# Migrated from airbyte-ci/connectors/base_images/README.md

ARG BASE_IMAGE=docker.io/python:3.11.11-slim-bookworm@sha256:6ed5bff4d7d377e2a27d9285553b8c21cfccc4f00881de1b24c9bc8d90016e82
FROM ${BASE_IMAGE}

RUN ln -snf /usr/share/zoneinfo/Etc/UTC /etc/localtime

# Set-up groups, users, and directories
RUN adduser --uid 1000 --system --group --no-create-home airbyte && \
    mkdir --mode 755 /custom_cache && \
    mkdir --mode 755 /airbyte && \
    chown airbyte:airbyte /airbyte

ENV PIP_CACHE_DIR=/custom_cache/pip
RUN pip install --upgrade pip==24.0 setuptools==70.0.0

ENV POETRY_VIRTUALENVS_CREATE=false
ENV POETRY_VIRTUALENVS_IN_PROJECT=false
ENV POETRY_NO_INTERACTION=1

RUN pip install poetry==1.8.4
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get dist-upgrade -y && \
    apt-get clean
RUN apt-get install -y socat=1.7.4.4-2
RUN apt-get update && \
    apt-get install -y \
        tesseract-ocr=5.3.0-2 \
        poppler-utils=22.12.0-2+b1

RUN mkdir -p 755 /usr/share/nltk_data
