FROM airbyte/base-python-test:dev

RUN apt-get update && apt-get install -y gcc bash && rm -rf /var/lib/apt/lists/*

ENV CODE_PATH="standardtest"
ENV AIRBYTE_TEST_MODULE="standardtest"
ENV AIRBYTE_TEST_PATH="TwilioStandardSourceTest"
ENV AIRBYTE_TEST_CASE=true

LABEL io.airbyte.version=0.1.0
LABEL io.airbyte.name=airbyte/source-twilio-singer-standard-test

WORKDIR /airbyte/integration_code
COPY $CODE_PATH ./$CODE_PATH

# copy all resources to the code path.
COPY secrets ./$CODE_PATH
COPY source_twilio_singer/*.json ./$CODE_PATH/
COPY sample_files/*.json ./$CODE_PATH/

COPY setup.py ./
RUN pip install -v ".[integration_tests]"

WORKDIR /airbyte

