#
# Copyright (c) 2021 Airbyte, Inc., all rights reserved.
#


import json
from datetime import datetime
from typing import Dict, Generator

from airbyte_cdk.logger import AirbyteLogger
from airbyte_cdk.models import (
    AirbyteCatalog,
    AirbyteConnectionStatus,
    AirbyteMessage,
    AirbyteRecordMessage,
    AirbyteStateMessage,
    AirbyteStream,
    ConfiguredAirbyteCatalog,
    Status,
    Type,
)
from airbyte_cdk.sources import Source
from faker import Faker


class SourceFaker(Source):
    def check(self, logger: AirbyteLogger, config: json) -> AirbyteConnectionStatus:
        """
        Tests if the input configuration can be used to successfully connect to the integration
            e.g: if a provided Stripe API token can be used to connect to the Stripe API.

        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json is as specified in
        the properties of the spec.json file

        :return: AirbyteConnectionStatus indicating a Success or Failure
        """

        # As this is an in-memory source, it always succeeds
        return AirbyteConnectionStatus(status=Status.SUCCEEDED)

    def discover(self, logger: AirbyteLogger, config: json) -> AirbyteCatalog:
        """
        Returns an AirbyteCatalog representing the available streams and fields in this integration.
        For example, given valid credentials to a Postgres database,
        returns an Airbyte catalog where each postgres table is a stream, and each table column is a field.

        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json is as specified in
        the properties of the spec.json file

        :return: AirbyteCatalog is an object describing a list of all available streams in this source.
            A stream is an AirbyteStream object that includes:
            - its stream name (or table name in the case of Postgres)
            - json_schema providing the specifications of expected schema for this stream (a list of columns described
            by their names and types)
        """
        streams = []

        # Fake Users
        stream_name = "Users"
        json_schema = {  # Example
            "$schema": "http://json-schema.org/draft-07/schema#",
            "type": "object",
            "properties": {
                "id": {"type": "number"},
                "created_at": {"type": "string", "format": "date-time", "airbyte_type": "timestamp_without_timezone"},
                "updated_at":{"type": "string", "format": "date-time", "airbyte_type": "timestamp_without_timezone"},
                "job": {"type": "string"},
                "company": {"type": "string"},
                "ssn": {"type": "string"},
                "residence": {"type": "string"},
                "current_location": {"type": "array", "items": "number"},
                "blood_group": {"type": "string"},
                "website": {"type": "array", "items": "string"},
                "username": {"type": "string"},
                "name": {"type": "string"},
                "sex": {"type": "string"},
                "address": {"type": "string"},
                "mail": {"type": "string"},
                "birthdate": {"type": "string", "format": "date"},
            },
        }
        streams.append(AirbyteStream(name=stream_name, json_schema=json_schema))

        return AirbyteCatalog(streams=streams)

    def read(
            self, logger: AirbyteLogger, config: json, catalog: ConfiguredAirbyteCatalog, state: Dict[str, any]
    ) -> Generator[AirbyteMessage, None, None]:
        """
        Returns a generator of the AirbyteMessages generated by reading the source with the given configuration,
        catalog, and state.

        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json is as specified in
            the properties of the spec.json file
        :param catalog: The input catalog is a ConfiguredAirbyteCatalog which is almost the same as AirbyteCatalog
            returned by discover(), but
        in addition, it's been configured in the UI! For each particular stream and field, there may have been provided
        with extra modifications such as: filtering streams and/or columns out, renaming some entities, etc
        :param state: When a Airbyte reads data from a source, it might need to keep a checkpoint cursor to resume
            replication in the future from that saved checkpoint.
            This is the object that is provided with state from previous runs and avoid replicating the entire set of
            data everytime.

        :return: A generator that produces a stream of AirbyteRecordMessage contained in AirbyteMessage object.
        """

        count = config["count"] if "count" in config else 0
        seed = config["seed"] if "seed" in config else -1
        Faker.seed(seed) if seed >= 0 else None
        fake = Faker()

        for stream in catalog.streams:
            total_records = 0

            if stream.stream.name == "Users":
                cursor = get_stream_cursor(state, stream.stream.name)
                total_records = total_records + cursor
                for i in range(1, (count - total_records) + 1):
                    data = emit_user(fake, i)
                    yield AirbyteMessage(
                        type=Type.RECORD,
                        record=AirbyteRecordMessage(
                            stream=stream.stream.name, data=data, emitted_at=int(datetime.now().timestamp()) * 1000
                        ),
                    )
                    total_records = total_records + 1

                yield emit_state(stream.stream.name, total_records)
            else:
                raise ValueError(stream.stream.name)

def get_stream_cursor(state, stream) -> int:
    cursor = (state[stream]["cursor"] or 0) if stream in state else 0
    return cursor


def emit_state(stream: str, value: int):
    message = AirbyteMessage(type=Type.STATE, state=AirbyteStateMessage(data={stream: {"cursor": value}}))
    return message


def emit_user(fake: Faker, idx: int):
    now = datetime.now()
    profile = fake.profile()
    metadata = {
        "id": idx,
        "created_at": now,
        "updated_at": now,
    }
    profile.update(metadata)
    return profile
