import {
  PUBLIC_API_SPEC_CACHE_PATH,
  PUBLIC_API_SIDEBAR_PATH,
} from "./constants";
import * as fs from "fs";
type Tag = {
  name: string;
  description?: string;
};

/**
 * Loads allowed tags from the cached public API OpenAPI specification
 */
const loadAllowedTags = (): string[] => {
  if (fs.existsSync(PUBLIC_API_SPEC_CACHE_PATH)) {
    try {
      const spec = JSON.parse(
        fs.readFileSync(PUBLIC_API_SPEC_CACHE_PATH, "utf8"),
      );
      // console.log('spec', spec);
      const allowed =
        spec.tags
          ?.filter((tag: Tag) => tag.name.includes("public"))
          .map((tag: Tag) => tag.name) || [];
      console.log("spec.tags", allowed);
      return allowed;
    } catch (e) {
      console.warn("Could not load OpenAPI spec for tag filtering:", e);
    }
  }
  return [];
};

/**
 * Loads and filters the public API sidebar based on allowed tags from the spec
 */
export const loadPublicApiSidebar = (): any[] => {
  if (fs.existsSync(PUBLIC_API_SIDEBAR_PATH)) {
    try {
      const sidebarModule = require(PUBLIC_API_SIDEBAR_PATH);

      // The sidebar.ts exports the array directly via: export default sidebar.apisidebar;
      let apiSidebarItems = sidebarModule.default || sidebarModule || [];

      // Filter to only show tags that are defined in the spec
      // apiSidebarItems = apiSidebarItems.filter((item: any) => {
      //   if (item.type !== "category") {
      //     return true;
      //   }
      //   console.log("item.label", item);

      //   return !item.label.includes("public");
      // });

      console.log(`Filtered API sidebar to ${apiSidebarItems.length} items`);
      return apiSidebarItems;
    } catch (e) {
      console.log("PUBLIC_API_SIDEBAR_PATH", PUBLIC_API_SIDEBAR_PATH);
      console.warn("Could not load pre-generated API sidebar:", e);
      return [];
    }
  } else {
    console.log(
      "PUBLIC_API_SIDEBAR_PATH does not exist",
      PUBLIC_API_SIDEBAR_PATH,
    );
    return [];
  }
};

/**
 * Helper function to find and replace the "api-reference" category in the developers sidebar
 */
export const replacePublicApiReferenceCategory = (
  items: any[],
  publicApiItems: any[],
): any[] => {
  return items.map((item) => {
    if (
      item.type === "category" &&
      item.label === "api-reference" &&
      item.items !== undefined
    ) {
      // Replace the api-reference category items with the filtered autogenerated API sidebar
      return {
        ...item,
        label: "Public Airbyte API",
        items: publicApiItems,
      };
    }

    if (item.items) {
      return {
        ...item,
        items: replacePublicApiReferenceCategory(item.items, publicApiItems),
      };
    }

    return item;
  });
};

/**
 * Generates the developers sidebar with public API integration
 */
export const generateDevelopersSidebar = async (args: any): Promise<any[]> => {
  const { defaultSidebarItemsGenerator } = args;

  // Get the default sidebar items
  const sidebarItems = await defaultSidebarItemsGenerator(args);
  // console.log("Default sidebar items loaded, total items:", sidebarItems);

  // Load and filter the public API sidebar based on allowed tags
  const publicApiItems = loadPublicApiSidebar();
  // console.log("Public API sidebar items loaded, total items:", publicApiItems);

  // Replace the "api-reference" category with the filtered API items
  return replacePublicApiReferenceCategory(sidebarItems, publicApiItems);
};
