name: PR unpin connection on merge
on: workflow_dispatch
#  workflow_dispatch:
#    inputs:
#      dry-run:
#        description: 'Dry run'
#        required: false
#        default: 'false'
#        type: boolean

#  pull_request:
#    types: [closed]

permissions:
  issues: write
  discussions: write

jobs:
  check-permissions:
    name: Resolve Input Variables
    runs-on: ubuntu-24.04
    steps:
      - name: Gather event metadata
        id: gather-metadata
        run: |
          # echo "author=${{github.event.sender.login}}" >> $GITHUB_OUTPUT
          if [[ "${{ github.event_name }}" == "issues" ]]; then
            echo "author=${{ github.event.issue.user.login }}" >> $GITHUB_OUTPUT
            echo "event-type=issue" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "discussion" ]]; then
            echo "author=${{ github.event.discussion.user.login }}" >> $GITHUB_OUTPUT
            echo "event-type=discussion" >> $GITHUB_OUTPUT
          # elif [[ "${{github.event_name}}" == "workflow_dispatch"]]; then
            # echo "author=${{github.event.sender.login}}" >> $GITHUB_OUTPUT
          fi

  ai-unpin:
    runs-on: ubuntu-latest
    name: AI Unpin Connections
    steps:
      - name: No-op
        if: github.event_name == 'workflow_dispatch'
        run: true
