name: PR unpin connections on merge
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry run'
        required: false
        default: 'false'
        type: boolean

#  pull_request:
#    types: [closed]

permissions: {}

jobs:
  ai-unpin:
    runs-on: ubuntu-latest
    name: AI Unpin Connections
    steps:
      - name: No-op
        run: true
