#!/bin/bash

set -eo pipefail

ABCON_URL=${ABCON:-file://$(pwd)/tools/con}
BUILD_DIR="build"
ABCON_CMD="$BUILD_DIR/abcon"

_download_con() {
    mkdir -p $BUILD_DIR
    curl -s "$ABCON_URL" -o "${ABCON_CMD}"
    chmod +x "${ABCON_CMD}"
    echo "Upgraded ($ABCON_URL)"
}

main() {
    [[ -f "${ABCON_CMD}" && -z "$UPGRADE" ]] || _download_con 1>&2
    "${ABCON_CMD}" "$@"
}

main "$@"
