import { defineConfig } from "orval";

export default defineConfig({
  api: {
    input: "../airbyte-api/src/main/openapi/config.yaml",
    output: {
      target: "./src/core/request/GeneratedApi.ts",
      override: {
        header: (info) => [
          `eslint-disable`,
          `Generated by orval 🍺`,
          `Do not edit manually.`,
          ...(info.title ? [info.title] : []),
          ...(info.description ? [info.description] : []),
          ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
        ],
        mutator: {
          path: "./src/core/request/apiOverride.ts",
          name: "apiOverride",
        },
      },
    },
  },
});
